<?php
// auto-generated by sfPropelAdmin
// date: 2009/03/04 10:50:21
?>
<td>
<div id="st_object_actions_td_frame">
<ul class="st_object_actions">     
  
       
      
    <?php if (method_exists($language, 'getIsSystemDefault') == false || (method_exists($language, 'getIsSystemDefault') &&  !$language->getIsSystemDefault())): ?>
    <?php if (!$language->getSystem()): ?>
  <li><?php echo link_to(image_tag('backend/icons/delete.gif', array('alt' => __('delete'), 'title' => __('delete'))), 'stLanguageBackend/delete?id='.$language->getId(), array (
  'post' => true,
  'confirm' => __('Jesteś pewien?'),
)) ?></li>
    <?php endif; ?>
    <?php endif; ?>
    
</ul>
</div>
</td>
