<?php
// auto-generated by sfPropelAdmin
// date: 2009/03/04 10:50:21
?>
<td>
    <?php if (!$language->getSystem()): ?>
        <?php echo checkbox_tag('language[selected][' . $language->getPrimaryKey() . ']', $language->getPrimaryKey(), false, array('class' => 'st_admin-language-select', 'onchange' => "$('language_action').disabled = true; var c = \$A(\$\$('input.st_admin-language-select')); c.each(function(checkbox) { if (checkbox.checked) { $('language_action').disabled = false; throw \$break; } })")) ?>
    <?php endif; ?>
</td>