---
package: 
  name: stTestPlugin
  stability: stable
  version: 1.0.1
  summary: Testy
  description: Testy funkcjonalnosci
  notes: Aktualizacja z 5.0.0 do 5.0.1
  maintainers: 
    Michal Prochowski: 
      role: lead
      user: michal
      email: michal.prochowski@sote.pl
