---
package: 
  name: stPropelActAsSortableBehaviorPlugin
  stability: stable
  version: 1.0.0
  summary: Propel sortable
  description: PropelActAsSortableBehavior
  notes: 1.0.0
  maintainers: 
    Marcin Butlak: 
      role: lead
      user: marcin
      email: marcin.butlak@sote.pl
