---
package: 
  name: stPropelAlternativeSchemaPlugin
  stability: stable
  version: 1.0.2.1
  summary: Obsluga alternatywnych schematow bazy danych
  description: Obsluga alternatywnych schematow bazy danych
  notes: |
    - Optymalizacja budowy modelu bazy danych
  maintainers: 
    Marcin Butlak: 
      role: lead
      user: marcin
      email: marcin.butlak@sote.pl
