generator:
    class:                          stAdminGenerator
    param:
        model_class:                PaymentType
        theme:                      simple
        applications:               [stOrder, stInvoicePlugin, stUser, stDelivery]

        head:
            package:                stPayment
        fields:
            name:                   {name: Nazwa, params: disabled=false}
            hide_for_wholesale:     {name: Ukryj dla klientów hurtowych}
            module_name:            {name: Sposób płatności}
            description:            {name: Opis , type: textarea_tag, params: size=40x5 rich=true tinymce_options='height:150,width:400,theme:"simple"' disabled=false}
            summary_description:    {name: Opis na stronie podsumowania zamówienia/płatności, type: textarea_tag, params: size=40x5 rich=true tinymce_options='height:150,width:400,theme:"simple"' disabled=false}
            active:                 {name: Aktywna}
            configuration:          {name: Konfiguracja płatności, hide_on_create: true, help: Aby płatność była widoczna po stronie sklepu musi być prawidłowo skonfigurowana}
    
        list:
            peer_method:            doSelectWithI18n
            peer_count_method:      doCountWithI18n
            title:                  Konfiguracja
            description:            Zarządzanie płatnościami klientów, wprowadzanie wpłat, konfiguracja płatności.
            display:                [=name, active, hide_for_wholesale]
            object_actions:
                _edit:              -
                _delete:            -
            actions:
                _create:            {name: Dodaj}
        
        edit:
            title:                  Edycja typu płatności
            description:            Zarządzanie płatnościami klientów, wprowadzanie wpłat, konfiguracja płatności.
            display:
                "Podstawowe dane":  [active, hide_for_wholesale, name, _module_name, _configuration, description, summary_description]
            fields:
                active:             {required: false}
                hide_for_wholesale: {required: false}
            actions:
                _delete:            {name: Usuń}
                _list:              {name: Lista}
                _save:              {name: Zapisz}
                _save_and_add:      {name: Zapisz i dodaj}