package:
  name: stAvailabilityPlugin
  stability: stable
  version: 7.4.2.2
  summary: Dostepnosc
  description: 'Definiowanie zakresow dostepnosci produktow'
  notes: |
    - Poprawka bledu 500 
  maintainers:
    'Krzysztof Beblo':
      role: lead
      user: krzysiek
      email: krzysztof.beblo@sote.pl
    'Pawel Byszewski':
      role: developer
      user: pawel
      email: pawel.byszewski@sote.pl
  dependency:
    stFrontend: 1.0.8.7
    stBackend: 1.0.4.7
    stDepositoryPlugin: 1.0.3.2
