package:
    name: soteshop_base
    stability: stable
    version: 6.9.7
    summary: 'SOTESHOP - Base'
    description: 'SOTESHOP - Base'
    notes: 'Release 6.9.7'
    maintainers:
        'Marek Jakubowicz':
            role: lead
            user: marek
            email: marek.jakubowicz@sote.pl
    dependency:
        appAddPricePlugin: 7.0.0.1
        appAdditionalDescPlugin: 7.1.0.6
        appBlueMediaPlugin: 7.1.0.0
        appCategoryHorizontalPlugin: 7.0.0.6
        appFacebookRemarketingPlugin: 7.0.0.12
        appOnlineCodesPlugin: 7.2.0.5
        appProductAttributesPlugin: 7.1.1.20
        stAccessoriesPlugin: 7.1.1.2
        stAdminGeneratorPlugin: 7.1.0.20
        stApplication: 1.0.0
        stAssetsLibraryPlugin: 7.2.1.30
        stAttributeTemplatePlugin: 1.0.1
        stAuthUsers: 7.0.2.2
        stAvailabilityPlugin: 7.4.2.2
        stBackend: 7.1.8.15
        stBackendFastMenuPlugin: 1.0.3.4
        stBase: 7.5.0.1
        stBasicPricePlugin: 7.0.1.1
        stBasket: 7.1.2.14
        stBlogPlugin: 7.1.7.10
        stBoxPlugin: 7.0.0.1
        stCaptchaGDPlugin: 7.0.0.0
        stCashBillPlugin: 7.1.0.3
        stCategory: 7.5.0.6
        stCategoryTreePlugin: 7.2.0.22
        stCombinePlugin: 1.0.0
        stCompatibilityPlugin: 7.1.0.6
        stConfigPlugin: 7.0.0.7
        stConfigurationPlugin: 7.0.1.4
        stCountriesPlugin: 7.0.0.0
        stCronPlugin: 1.0.1
        stCrossellingPlugin: 7.1.0.1
        stCurrencyPlugin: 7.4.0.1
        stDelivery: 7.4.0.22
        stDepositoryPlugin: 7.1.1.1
        stDiscountPlugin: 7.1.0.17
        stDocPlugin: 7.0.0.4
        stErrorPlugin: 2.1.0.4
        stExtendImportExportPlugin: 7.1.0.0
        stExtjs2Plugin: '7.3'
        stFastCacheSymfony: 7.2.0.8
        stFixturesAir: 7.0.0
        stFixturesArgentorwd: 7.0.0.5
        stFixturesBianco: 7.0.6
        stFixturesCutlery: 7.0.0.2
        stFixturesElegante: 7.0.6
        stFixturesFashion: 7.0.0.2
        stFixturesGiallo: 7.0.0.3
        stFixturesMarrone: 7.0.0.2
        stFixturesModerno: 7.0.0.1
        stFixturesResponsive: 7.0.0.126
        stFixturesStart: 2.2.5.2
        stFrontend: 7.0.1.9
        stGiftCardPlugin: 7.1.0.9
        stGoogleAnalyticsPlugin: 7.0.0.7
        stGoogleShoppingPlugin: 7.0.8.5
        stGroupPricePlugin: 7.0.2.2
        stGuardPlugin: 7.4.0.2
        stHtaccessPlugin: 7.0.0.1
        stImportExportPlugin: 7.0.0.27
        stInBankPlugin: 7.0.0.16
        stInvoicePlugin: 7.0.5.6
        stJavascriptDropMenuPlugin: 1.2.0.1
        stLanguagePlugin: 7.1.1.17
        stLockPlugin: 7.0.9.4
        stMailPlugin: 7.0.3.8
        stMigration: 7.4.0.0
        stMigrationSoteshopPlugin: 1.2.0.26
        stMinifyPlugin: 7.2.0.1
        stMoneybookersPlugin: 7.1.0.2
        stNavigationPlugin: 7.1.0.8
        stNewsletterPlugin: 7.5.0.11
        stNiftyPlugin: 7.2.0.0
        stOptimizationPlugin: 7.1.1.0
        stOrder: 7.4.4.21
        stPaczkomatyPlugin: 7.5.1.7
        stPartnerPlugin: 2.0.0
        stPayByNetPlugin: 7.1.1.12
        stPayNowPlugin: 7.0.0.11
        stPayment: 7.4.0.22
        stPaypalPlugin: 7.2.0.14
        stPear: 7.4.0.1
        stPhotoGalleryPlugin: 2.0.0.8
        stPocztaPolskaPlugin: 7.4.0.23
        stPointsPlugin: 7.0.5.4
        stPositioningPlugin: 7.4.1.4
        stPriceCompare: 7.4.0.6
        stProducer: 7.1.0.1
        stProduct: 7.4.3.5
        stProductComparePlugin: 2.2.1.1
        stProductGroup: 7.0.4.13
        stProductOptionsPlugin: 7.2.1.20
        stProgressBarPlugin: 7.1.0.2
        stPromoteProductsInBasketPlugin: 2.1.1.0
        stPropelActAsNestedSetBehaviorPlugin: 1.0.2.4
        stPropelActAsSortableBehaviorPlugin: 1.0.0
        stPropelAlternativeSchemaPlugin: 1.0.2.1
        stPropelOptimizerPlugin: 7.4.0.0
        stPropelSeoUrlBehaviorPlugin: 1.2.0.11
        stPrototypePlugin: 2.0.0
        stQuestionPlugin: 7.0.0.8
        stRSSPlugin: 1.0.1
        stRegister: 7.0.0.2
        stReminderPlugin: 2.0.0
        stReportPlugin: 7.0.0.19
        stReview: 7.4.2.7
        stSantanderRatyPlugin: 7.0.0.19
        stSearchPlugin: 7.5.1.4
        stSecurityPlugin: 7.1.2.2
        stShopInfoPlugin: 7.0.0.1
        stSlideBannerPlugin: 7.2.0.11
        stSmartyPlugin: 7.4.0.11
        stSocialLinksPlugin: 7.0.1.4
        stStatsPlugin: 1.0.2.5
        stSuperCacheFilter: 7.2.0.8
        stSwiftPlugin: 1.2.0.2
        stSymfonyUpdate: 7.5.0.3
        stTCPDFPlugin: 7.4.0.0
        stTabNavigatorPlugin: 7.2.0.0
        stTaxPlugin: 7.0.0.9
        stTestPlugin: 1.0.1
        stTextPlugin: 2.0.0.1
        stTheme1Cutlery: 7.0.2.3
        stTheme1Elegante: 7.0.0.14
        stTheme1Fashionrwd: 7.0.2.5
        stTheme1Giallorwd: 7.0.0.19
        stTheme1Marrone: 7.0.0.20
        stTheme1Modernorwd: 7.0.1.6
        stThemeAirSports: 7.0.1.2
        stThemeArgentorwd: 7.2.2.2
        stThemeBianco: 7.1.1.3
        stThemeDefault2: 2.1.3.7
        stThemePlugin: 7.1.0.28
        stThemeResponsive: 7.8.2.4
        stThumbnailPlugin: 7.0.1.15
        stTinyMCEPlugin: 7.2.0.31
        stTooltipPlugin: 1.0.1.4
        stTranslationCsPlugin: 7.0.5.0
        stTranslationDePlugin: 7.0.6.1
        stTranslationEsPlugin: 7.0.5.0
        stTranslationFrPlugin: 7.0.5.1
        stTranslationItPlugin: 7.0.5.0
        stTranslationNoPlugin: 7.0.5.0
        stTranslationPtPlugin: 7.0.5.0
        stTranslationRuPlugin: 7.0.5.0
        stTranslationSkPlugin: 7.0.5.1
        stTranslationZhPlugin: 7.0.5.0
        stTrustPlugin: 1.0.1.5
        stTrustedShopsPlugin: 7.2.6.2
        stUpdaterPlugin: 7.1.0.6
        stUser: 7.3.1.13
        stWebApiPlugin: 7.5.0.0
        stWebBrowserPlugin: 7.4.0.0
        stWebpagePlugin: 7.5.0.7
        stWholesalePlugin: 7.0.0.3
        stXssSafePlugin: 1.0.0.2
