package:
  name: stQuestionPlugin
  stability: stable
  version: 7.0.0.8
  summary: Zapytania
  description: 'Zarzadzanie zapytaniami w sklepie'
  notes: |
     - Aktualizacja RODO
  maintainers:
    'Paweł Byszewski':
      role: lead
      user: pawel
      email: pawel.byszewski@sote.pl
  dependency:
    stFrontend: 1.0.6
    stBackend: 1.0.3
    stProduct: 1.0.15.6
    stMailPlugin: 1.0.1
