<?php
// auto-generated by sfPropelAdmin
// date: 2014/10/08 10:08:14
?>
<?php echo form_tag('stBasicPriceBackend/save', array(
  'id'        => 'admin_edit_form',
  'name'      => 'admin_edit_form',
  'class'     => 'admin_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($basic_price_unit_measure, 'getId') ?>


<fieldset id="sf_fieldset_none">
<div class="content" id="sf_fieldset_none_slide">
<?php if (!$sf_user->getParameter('hide', false,'stBasicPriceBackend/edit/fields/is_default')): ?>
<div class="row row_is_default">

<label for="basic_price_unit_measure_is_default">
  <?php echo __($labels['basic_price_unit_measure{is_default}'], array(), 'stBasicPriceBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('basic_price_unit_measure{is_default}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('basic_price_unit_measure{is_default}')): ?>
    <?php echo form_error('basic_price_unit_measure{is_default}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>
<?php if ($basic_price_unit_measure->getIsSystem()!=1 || $basic_price_unit_measure->getId()==null): ?>
 <?php echo object_checkbox_tag($basic_price_unit_measure, 'getIsDefault', array (
  'control_name' => 'basic_price_unit_measure[is_default]',
)); ?> 
<?php else: ?>
 <?php echo object_checkbox_tag($basic_price_unit_measure, 'getIsDefault', array (
  'control_name' => 'basic_price_unit_measure[is_default]',
  'disabled' => true,
)); ?> 
<?php endif; ?>

  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

<?php if (!$sf_user->getParameter('hide', false,'stBasicPriceBackend/edit/fields/unit_name')): ?>
<div class="row row_unit_name">

<label for="basic_price_unit_measure_unit_name">
  <?php echo __($labels['basic_price_unit_measure{unit_name}'], array(), 'stBasicPriceBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('basic_price_unit_measure{unit_name}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('basic_price_unit_measure{unit_name}')): ?>
    <?php echo form_error('basic_price_unit_measure{unit_name}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

<?php if ($basic_price_unit_measure->getIsSystem()!=1 || $basic_price_unit_measure->getId()==null): ?>
 <?php echo object_input_tag($basic_price_unit_measure, 'getUnitName', array (
  'size' => 32,
  'control_name' => 'basic_price_unit_measure[unit_name]',
)); ?> 

<?php else: ?>
<?php echo object_input_tag($basic_price_unit_measure, 'getUnitName', array (
  'size' => 32,
  'control_name' => 'basic_price_unit_measure[unit_name]',
  'disabled' => true,
)); ?>
<?php endif; ?>

  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

<?php if (!$sf_user->getParameter('hide', false,'stBasicPriceBackend/edit/fields/multiplier')): ?>
<div class="row row_multiplier">

<label for="basic_price_unit_measure_multiplier">
  <?php echo __($labels['basic_price_unit_measure{multiplier}'], array(), 'stBasicPriceBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('basic_price_unit_measure{multiplier}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('basic_price_unit_measure{multiplier}')): ?>
    <?php echo form_error('basic_price_unit_measure{multiplier}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

<?php if ($basic_price_unit_measure->getIsSystem()!=1 || $basic_price_unit_measure->getId()==null): ?>
<?php echo object_input_tag($basic_price_unit_measure, 'getMultiplier', array (
  'size' => 7,
  'control_name' => 'basic_price_unit_measure[multiplier]',
)); ?>
<?php else: ?> 
<?php echo object_input_tag($basic_price_unit_measure, 'getMultiplier', array (
  'size' => 7,
  'control_name' => 'basic_price_unit_measure[multiplier]',
  'disabled' => true,
)); ?>
<?php endif; ?>
  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

<?php if (!$sf_user->getParameter('hide', false,'stBasicPriceBackend/edit/fields/unit_symbol')): ?>
<div class="row row_unit_symbol">

<label for="basic_price_unit_measure_unit_symbol" class="required" >
  <?php echo __($labels['basic_price_unit_measure{unit_symbol}'], array(), 'stBasicPriceBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('basic_price_unit_measure{unit_symbol}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('basic_price_unit_measure{unit_symbol}')): ?>
    <?php echo form_error('basic_price_unit_measure{unit_symbol}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

<?php if ($basic_price_unit_measure->getIsSystem()!=1 || $basic_price_unit_measure->getId()==null): ?>
 <?php echo object_input_tag($basic_price_unit_measure, 'getUnitSymbol', array (
  'size' => 20,
  'control_name' => 'basic_price_unit_measure[unit_symbol]',
)); ?> 
<?php else: ?>
<?php echo object_input_tag($basic_price_unit_measure, 'getUnitSymbol', array (
  'size' => 20,
  'control_name' => 'basic_price_unit_measure[unit_symbol]',
  'disabled' => true,
)); ?> 
<?php endif; ?>


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

<?php if (!$sf_user->getParameter('hide', false,'stBasicPriceBackend/edit/fields/unit_group')): ?>
<div class="row row_unit_group">

<label for="basic_price_unit_measure_unit_group" class="required" >
  <?php echo __($labels['basic_price_unit_measure{unit_group}'], array(), 'stBasicPriceBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('basic_price_unit_measure{unit_group}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('basic_price_unit_measure{unit_group}')): ?>
    <?php echo form_error('basic_price_unit_measure{unit_group}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

<?php if ($basic_price_unit_measure->getIsSystem()!=1 || $basic_price_unit_measure->getId()==null): ?>
 <?php echo object_input_tag($basic_price_unit_measure, 'getUnitGroup', array (
  'size' => 20,
  'control_name' => 'basic_price_unit_measure[unit_group]',
)); ?> 
<?php else: ?>
 <?php echo object_input_tag($basic_price_unit_measure, 'getUnitGroup', array (
  'size' => 20,
  'control_name' => 'basic_price_unit_measure[unit_group]',
  'disabled' => true,
)); ?>
<?php endif; ?>

  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

</div>
</fieldset>

<div id="edit_actions"><?php st_include_partial('edit_actions', array('basic_price_unit_measure' => $basic_price_unit_measure, 'forward_parameters' => $forward_parameters)) ?></div>

</form>

<script type="text/javascript">
jQuery(function($) {
    $(document).ready(function() {
        $('#edit_actions').stickyBox();
    });

});
</script>
