<?php
// auto-generated by sfPropelAdmin
// date: 2014/10/08 09:44:40
?>
<?php echo st_get_admin_actions_head('style="float: left"') ?>
<?php if (method_exists($basic_price_unit_measure, 'getIsSystemDefault') == false || (method_exists($basic_price_unit_measure, 'getIsSystemDefault') && !$basic_price_unit_measure->getIsSystemDefault())): ?>
<?php if ($basic_price_unit_measure->getId() && $basic_price_unit_measure->getIsSystem()!=1): ?>
		    
  <?php echo st_get_admin_action('delete', __('Usuń', null, 'stAdminGeneratorPlugin'), 'stBasicPriceBackend/delete?id='.$basic_price_unit_measure->getId(), array("confirm" => __("Jesteś pewien?"),"name" => "delete",)) ?><?php endif; ?>

<?php endif; ?>
</ul>

<?php echo st_get_admin_actions_head('style="float: right"') ?>

      <?php echo st_get_admin_action('list', __('Jednostki', null, 'stBasicPriceBackend'), 'stBasicPriceBackend/list', array("name" => "list",)) ?>      
<?php if ($basic_price_unit_measure->getIsSystem()!=1 || $basic_price_unit_measure->getId()==null): ?>      
      <?php echo st_get_admin_action('save', __('Zapisz', null, 'stAdminGeneratorPlugin'), null, array("name" => "save",)) ?>      <?php echo st_get_admin_action('save_and_add', __('Zapisz i dodaj kolejny', null, 'stAdminGeneratorPlugin'), null, array("name" => "save_and_add",)) ?>  <?php echo st_get_admin_actions_foot() ?>
      <?php endif; ?>