<?php
// auto-generated by sfPropelAdmin
// date: 2014/10/08 09:47:59
?>
<td>
<ul class="st_object_actions">     
  
  
    <?php if (method_exists($basic_price_unit_measure, 'getIsSystemDefault') == false || (method_exists($basic_price_unit_measure, 'getIsSystemDefault') &&  !$basic_price_unit_measure->getIsSystemDefault())): ?>
    
  <li>
      <?php if ($basic_price_unit_measure->getIsSystem()!=1): ?>    
      <a href="<?php echo url_for('stBasicPriceBackend/delete?id='.$basic_price_unit_measure->getId()) ?>" onclick="return confirm('<?php echo __('Jesteś pewien?') ?>');"><img src="/images/backend/beta/icons/16x16/remove.png" title="<?php echo __('delete') ?>" class="tooltip" /></a>
      <?php endif; ?>
  </li>
    
    <?php endif; ?>
    
</ul>
</td>
