---
package: 
  name: stSklepy24Plugin
  stability: stable
  version: 2.0.0.0
  summary: Sklepy24
  description: Zarzadzanie porownywarka cen Sklepy24
  notes: |
    - Poprawka listy produtkow do eksportu.
  maintainers: 
    Michal Prochowski: 
      role: lead
      user: michal
      email: michal.prochowski@sote.pl
  dependency: 
    stPriceCompare: 1.0.3.10