package:
  name: stEcardPlugin
  stability: stable
  version: 7.1.0.7
  summary: eCard
  description: 'Konfiguracja platnosci eCard.'
  notes: |
    - Dostosowanie do pakietu do zmian w stPayment
  maintainers:
    'Michal Prochowski':
      role: lead
      user: michal
      email: michal.prochowski@sote.pl
  dependency:
    stPayment: 1.0.5.1
    stConfigurationPlugin: 1.0.3.6
