---
package: 
  name: stPear
  stability: stable
  version: 7.4.0.1
  summary: Pakiet aktualizacyjny PEAR
  description: Pakiet aktualizacyjny PEAR
  notes: |
     - Aktualizacja dla PHP 7.0.x oraz 7.1.x
  maintainers: 
    Michal Prochowski: 
      role: lead
      user: michal
      email: michal.prochowski@sote.pl