<?php
// auto-generated by sfPropelAdmin
// date: 2008/10/31 11:38:34
?>
<td>
    <?php if($user_data->getIsDefault()!=1): ?>
    <?php echo checkbox_tag('user_data[selected][' . $user_data->getPrimaryKey() . ']', $user_data->getPrimaryKey(), false, array('class' => 'st_admin-user_data-select', 'onchange' => "$('user_data_action').disabled = true; var c = \$A(\$\$('input.st_admin-user_data-select')); c.each(function(checkbox) { if (checkbox.checked) { $('user_data_action').disabled = false; throw \$break; } })")) ?>
    <?php endif; ?>
</td>