<?php
// auto-generated by sfPropelAdmin
// date: 2019/10/21 13:19:15
?>
<?php if (SF_ENVIRONMENT == 'dev'): ?>
<?php echo st_get_admin_actions_head('style="margin-top: 10px;"') ?>
<?php echo st_get_admin_action('create', __('Dodaj', null, 'stAdminGeneratorPlugin'), 'stThemeBackend/contentCreate?theme_id='.$forward_parameters['theme_id'], array("name" => "create",)) ?>
<?php echo st_get_admin_actions_foot() ?>
<?php endif ?>
