<?php
// auto-generated by sfPropelAdmin
// date: 2016/05/06 14:20:44
?>
<?php echo st_get_admin_head('stGoogleShoppingPlugin', $title, array('shortcuts' => NULL, 'culture' => isset($culture) ? $culture : null, 'route' => isset($route) ? $route : null)) ?>

<?php
$config = stConfig::getInstance(sfContext::getInstance(), 'stSecurityBackend');
//echo $config->get('ssl');

if($config->get('ssl')!="shop"){
?>
<div style="margin:10px; color: #000;padding: 15px; border: 1px solid #ccc; background-color: #eee; border-radius: 5px 5px 5px 5px;">
    <?php echo __("Do poprawnego działania Google Shoping niezbędne jest posiadanie certyfikatu SSL.") ?><br/>
    <?php echo __("Jego brak może skutkować zawieszeniem konta Google Merchant.") ?><br/>
    <?php echo __("Więcej informacji na ten temat można znaleźć na stronach pomocy") ?>    
    <a href="https://goo.gl/r3h2wO" target="_blank">Google Merchant Center</a>
</div>

<?php 
}
?>