<?php
// auto-generated by sfPropelAdmin
// date: 2016/05/06 10:27:54
?>
<?php echo st_get_admin_actions_head('style="margin-top: 10px;"') ?>
          <?php echo st_get_admin_action('delete', __('Wypisz wszystkie'), 'stGoogleShoppingBackend/deleteAll', array("name" => "delete",)) ?>          <?php echo st_get_admin_action('add', __('Przypisz wszystkie'), 'stGoogleShoppingBackend/addAll', array("name" => "add",)) ?>  <?php echo st_get_admin_actions_foot() ?>
