---
package: 
  name: stAttributeTemplatePlugin
  stability: stable
  version: 1.0.1
  summary: Atrybuty
  description: Zarzadzanie szablonami atrybutow produktu
  notes: Aktualizacja z 5.0.0 do 5.0.1
  maintainers: 
    Marcin Butlak: 
      role: lead
      user: marcin
      email: marcin.butlak@sote.pl
    Daniel Mendalka: 
      role: contributor
      user: daniel
      email: daniel.mendalka@sote.pl
  dependency: 
    stFrontend: 1.0.4
    stBackend: 1.0.2
    stProduct: 1.0.4
    stPropelActAsSortableBehaviorPlugin: 1.0.0
