<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/16 10:56:44
?>
<?php echo st_get_admin_head(array('@stPocztaPolskaBackend?action=list', __('Poczta Polska'), '/images/backend/main/icons/red/stPocztaPolskaPlugin.png'), $title, array('shortcuts' => NULL, 'culture' => isset($culture) ? $culture : null, 'route' => isset($route) ? $route : null)) ?>

<?php if ($sf_user->getParameter('bufor', null, 'soteshop/stPocztaPolska')): $bufor = $sf_user->getParameter('bufor', null, 'soteshop/stPocztaPolska') ?>
    <form action="<?php echo st_url_for('@stPocztaPolskaBackend?action=updateBufor&bufor_id='.$bufor->getBuforId()) ?>" method="post" class="admin_form" id="st_poczta_polska_bufor_form" style="margin: 0px 10px 10px 10px; position: relative;">
        <div class="save-ok" style="display: none">
            <h2><?php echo __('Twoje zmiany zostały zapisane', null, 'stAdminGeneratorPlugin') ?><span></span></h2>
        </div>
        <fieldset>
            <div class="content">
                <?php echo st_admin_get_form_field('bufor[data_nadania]', __('Planowana data nadania'), $bufor->getDataNadania(), 'input_date_tag', array(
                      'rich' => true,
                      'withtime' => false,
                      'calendar_button_img' => '/sf/sf_admin/images/date.png',
                      'calendar_options' => "
                        'onUpdate': function() {
                            jQuery('#st_poczta_polska_bufor_form').submit();
                        }
                      "
                )) ?>
                <?php echo st_admin_get_form_field('bufor[urzad_nadania]', __('Urząd nadania'), $bufor->getUrzadNadania(), 'st_urzedy_nadania_select') ?>            
            </div>
        </fieldset>
    </form>
<?php endif ?>

<script type="text/javascript">
    jQuery(function($) {
        $('#bufor_urzad_nadania').change(function() {
            $('#st_poczta_polska_bufor_form').submit();
        });

        $('#st_poczta_polska_bufor_form').submit(function() {
            var form = $(this);
            var message = form.find('.save-ok');

            message.hide();

            $.post(form.attr('action'), form.serialize(), function(data) {
                if (data.error) {
                    message.find('span').html(" - "+data.error.errorDesc);
                } else {
                    message.find('span').html('');
                }

                message.show();

                $(document).trigger('preloader', 'close');
            });

            return false;
        });
    }); 
</script>