<?php
// auto-generated by sfPropelAdmin
// date: 2013/02/18 16:32:12
?>
<?php echo st_get_admin_actions_head('style="float: left"') ?>
<?php if (method_exists($add_group_price, 'getIsSystemDefault') == false || (method_exists($add_group_price, 'getIsSystemDefault') && !$add_group_price->getIsSystemDefault())): ?>
		<?php if ($add_group_price->getId() && $add_group_price->getCurrencyId()): ?>
<?php echo st_get_admin_action('delete', __('Usuń', null, 'stAdminGeneratorPlugin'), 'stGroupPriceBackend/addGroupPriceDelete?id='.$add_group_price->getId().'&currency_id='.$add_group_price->getCurrencyId().'&group_price_id='.$forward_parameters['group_price_id'], array("confirm" => __("Jesteś pewien?"),"name" => "delete",)) ?><?php endif; ?>
<?php endif; ?>
</ul>

<?php echo st_get_admin_actions_head('style="float: right"') ?>

    <ul class="admin_actions" style="float: right">
          <?php echo st_get_admin_action('list', __('Pokaż listę', null, 'stAdminGeneratorPlugin'), 'stGroupPriceBackend/addGroupPriceList?group_price_id='.$forward_parameters['group_price_id'], array("name" => "list",)) ?>      
          <li class="action-sync" style="display: list-item;"><input type="submit" style="background-image: url(/images/backend/icons/save.png)" value="Synchronizuj" name="save_and_add"></li>      
          <li class="action-save" style="display: list-item;"><input type="submit" style="background-image: url(/images/backend/icons/save.png)" value="Zapisz" name="save"></li>  
    </ul>

<?php echo st_get_admin_actions_foot() ?>