<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/10 15:21:05
?>
<?php echo st_get_admin_actions_head('style="margin-top: 10px; float: right"') ?>
      <?php echo st_get_admin_action('list', __('Lista', array(), 'stAdminGeneratorPlugin'), 'sfGuardUser/list', array (
)) ?>      

 <?php if($sf_guard_user->getId() == $sf_user->getGuardUser()->getId() || $sf_user->getGuardUser()->getIsSuperAdmin()): ?>
 
    <?php echo st_get_admin_action('save', __('Zapisz', array(), 'stAdminGeneratorPlugin'), null, array (
      'name' => 'save',
    )) ?>
    
<?php endif; ?>

<?php echo st_get_admin_actions_foot() ?>
