<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/10 15:21:05
?>
<td>

<div id="st_object_actions_td_frame">
<ul class="st_object_actions">     
  
        
  
    <?php if($sf_user->getGuardUser()->getIsSuperAdmin()): ?>
    
        <?php if($sf_guard_user->getId() != $sf_user->getGuardUser()->getId()): ?>
    
            <?php if (method_exists($sf_guard_user, 'getIsSystemDefault') == false || (method_exists($sf_guard_user, 'getIsSystemDefault') &&  !$sf_guard_user->getIsSystemDefault())): ?>
    
  <li><?php echo link_to(image_tag('backend/icons/delete.gif', array('alt' => __('delete'), 'title' => __('delete'))), 'sfGuardUser/delete?id='.$sf_guard_user->getId(), array (
  'post' => true,
  'confirm' => __('Jesteś pewien?', array(), 'stAdminGeneratorPlugin'),
)) ?></li>
            <?php endif; ?>
            
        <?php endif; ?>
        
    <?php endif; ?>
    
</ul>
</div>

</td>