<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/10 15:21:05
?>
<?php if($sf_user->getGuardUser()->getIsSuperAdmin()): ?>
<?php echo st_get_admin_actions_head('style="margin-top: 10px; float: right"') ?>
          <?php echo st_get_admin_action('create', __('Dodaj'), 'sfGuardUser/create', array (
)) ?>  <?php echo st_get_admin_actions_foot() ?>
<?php endif; ?>