<?php
// auto-generated by sfPropelAdmin
// date: 2009/09/10 15:21:05
?>
<td>
        <ul class="st_object_actions">
            <li><?php echo link_to(image_tag('backend/icons/edit.gif', array('alt' => __('edit'), 'title' => __('edit'))), 'sfGuardUser/edit?id='.$sf_guard_user->getId()) ?></li>  
        </ul>
</td>
