package:
  name: stOkazjePlugin
  stability: stable
  version: 2.0.0.3
  summary: Okazje
  description: 'Zarzadzanie porownywarka cen Okazje'
  notes: |
    - Poprawka listy produtkow do eksportu.
  maintainers:
    'Michal Prochowski':
      role: lead
      user: michal
      email: michal.prochowski@sote.pl
  dependency:
    stPriceCompare: 1.0.3
