<?php
// auto-generated by sfPropelAdmin
// date: 2011/03/07 11:41:04
?>

<?php echo form_tag('stReminderBackend/list', array('id' => 'st_record_list-form')) ?>
<?php echo input_hidden_tag('page', $pager->getPage()) ?>
<table cellspacing="0" class="st_record_list" width="100%">

	<thead>

		<tr>
		<?php st_include_partial('list_pager', array('pager' => $pager, 'forward_parameters' => $forward_parameters, 'backend_alert_action_select_options' => $backend_alert_action_select_options, 'prefix' => 'head')) ?>
		</tr>

		<tr>
			<?php st_include_partial('list_th_tabular', array('forward_parameters' => $forward_parameters)) ?>
		</tr>
	</thead>
	<tbody>
	<?php $i = 1; $k=1; foreach ($pager->getResults() as $backend_alert): $odd = fmod(++$i, 2) ?>
	<?php if ($odd): ?>
		<tr class="st_row-highlight">
		<?php else: ?>
			<tr>
			<?php endif; ?>
			<?php st_include_partial('list_td_action_edit', array('backend_alert' => $backend_alert, 'forward_parameters' => $forward_parameters)) ?>
			<?php if ($backend_alert_action_select_options): ?>
			<?php st_include_partial('list_td_action_select', array('backend_alert' => $backend_alert, 'forward_parameters' => $forward_parameters)) ?>
			<?php else: ?>
				<td></td>
				<?php endif; ?>
				<?php st_include_partial('list_td_tabular', array('backend_alert' => $backend_alert, 'forward_parameters' => $forward_parameters)) ?>
				<?php st_include_partial('list_td_actions', array('backend_alert' => $backend_alert, 'forward_parameters' => $forward_parameters)) ?>
			</tr>
			<?php endforeach; ?>
			<?php if (!$pager->getNbResults()): ?>
			<tr>
				<td colspan="6"><?php echo __('Brak rekordów - zmień kryteria wyszukiwania', null, 'stAdminGeneratorPlugin') ?>
				</td>
			</tr>
			<?php endif; ?>
	
	</tbody>
	<tfoot>
		<tr>
		<?php st_include_partial('list_pager', array('pager' => $pager, 'forward_parameters' => $forward_parameters, 'backend_alert_action_select_options' => $backend_alert_action_select_options, 'prefix' => 'foot')) ?>
		</tr>
	</tfoot>
</table>

</form>
