package:
  name: stFixturesLazuli
  stability: stable
  version: 7.0.2
  summary: Dane dla tematu Lazuli
  description: Dane dla tematu Lazuli
  notes: Przykladowe dane dla tematu Lazuli
  maintainers:
    'Krzysztof Beblo':
      role: lead
      user: krzysiek
      email: krzysztof.beblo@sote.pl
