<?php
// auto-generated by sfPropelAdmin
// date: 2016/04/19 11:30:48
?>
<div class="application-menu">
    <ul>
        <?php 
        $action2 = sfContext::getInstance()->getActionName();

        foreach ($items as $action => $name): 
        	$url = url_for($action);
        	if ($action2 == "edit")
        	{
        		if (strpos($action, "stPositioningBackend/edit?")!== false)
        		{
        			$class="selected";
        		}else{
        			$class="none";
        		}
        	}else{

	        	if($selected_item_path == $url)
	        	{
	        		$class="selected";
	        	}else{
	        		$class="none";
	        	}
        	}
        	?>
            <li class="<?php echo $class;?>"><a href="<?php echo $url ?>"><?php echo $name ?></a></li>
        <?php endforeach; ?>
    </ul>

    <br style="clear: left" />
</div>