<?php
// auto-generated by sfPropelAdmin
// date: 2008/08/12 15:39:37
?>
<td>
<ul class="st_object_actions">     
  <nobr>
  <li><?php echo link_to(image_tag('backend/icons/edit.gif', array('alt' => __('edit'), 'title' => __('edit'))), 'sfGuardUser/edit?id='.$sf_guard_user->getId()) ?></li>
  <?php if($sf_flash->get('enable_delete',false)): ?>
  <li><?php echo link_to(image_tag('backend/icons/delete.gif', array('alt' => __('delete'), 'title' => __('delete'))), 'sfGuardUser/delete?id='.$sf_guard_user->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
)) ?></li>
    <?php endif; ?>
  </nobr>
</ul>
</td>
