package:
  name: stCrossellingPlugin
  stability: stable
  version: 7.1.0.1
  summary: Crosselling
  description: Crosselling
  notes: |
    - Aktualizacja modulu.
  maintainers:
    'Michal Prochowski':
      role: lead
      user: michal
      email: michal.prochowski@sote.pl
  dependency:
    stPromoteProductsInBasketPlugin: 1.0.1.1
    stProduct: 1.0.13.14
