<?php
// auto-generated by sfPropelAdmin
// date: 2009/10/28 11:49:18
?>
<?php if ($sf_request->getError('delete')): ?>
<div class="form-errors">
  <h2><?php echo __('Błąd podczas usuwania.', array('%name%' => 'Product')) ?></h2>
  <dl>
    <dt><?php echo __('Uwaga:')?></dt>
    <dd><?php echo $sf_request->getError('delete') ?></dd>
  </dl>
</div>
<?php elseif ($sf_flash->has('notice')): ?>
<div class="save-ok">
<h2><?php echo __($sf_flash->get('notice')) ?></h2>
</div>
<?php endif; ?>
<?php if ($sf_flash->has('warning')): ?>
<div class="form-errors">
<h2><?php echo __($sf_flash->get('warning')) ?></h2>
</div>
<?php endif; ?>