---
package: 
  name: stProgressBarPlugin
  stability: stable
  version: 7.1.0.2
  summary: Pasek postepu
  description: Pasek postepu
  notes: |
    - Poprawka wyswietlania paska postepu
  maintainers: 
    Piotr Halas: 
      role: lead
      user: piotr
      email: piotr.halas@sote.pl