---
package: 
  name: stHandeloPlugin
  stability: stable
  version: 1.2.0.0
  summary: Handelo
  description: Zarzadzanie porownywarka cen Handelo
  notes: |
    - Wylaczenie integracji z serwisem.
  maintainers: 
    Michal Prochowski: 
      role: lead
      user: michal
      email: michal.prochowski@sote.pl
  dependency: 
    stPriceCompare: 1.0.3