package:
  name: stPayment
  stability: stable
  version: 7.4.0.22
  summary: Platnosci
  description: 'Zarzadzanie platnosciami klientow, wprowadzanie wplat, konfiguracja platnosci.'
  notes: |
     - Poprawka braku oplaconego zamowienia na liscie zamowien
  maintainers:
    'Michal Prochowski':
      role: lead
      user: michal
      email: michal.prochowski@sote.pl
  dependency:
    stFrontend: 1.0.6
    stBackend: 1.0.3
    stUser: 1.0.4
    stInBankPlugin: 7.0.0.9
