<?php
// auto-generated by sfPropelAdmin
// date: 2009/05/15 13:55:01
?>
<!--<ul class="st_record_list-actions">
    <li>
        <?php echo link_to_function(image_tag('backend/icons/uncheck_all.png', array('alt' => __('Odznacz wszystkie', array(), 'stAdminGeneratorPlugin'))), "var selects = \$\$('input.st_admin-mail_description-select'); selects.each(function(input) { input.checked = false; });") ?>
    </li>
    <li>
        <?php echo link_to_function(image_tag('backend/icons/check_all.png', array('alt' => __('Zaznacz wszystkie', array(), 'stAdminGeneratorPlugin'))), "var selects = \$\$('input.st_admin-mail_description-select'); selects.each(function(input) { input.checked = true; });") ?>
    </li>
<?php foreach($mail_description_action_select_options['NONE'] as $action => $label): ?>
    <li>
        <?php echo link_to($label, '#', array('onclick' => "$('st_record_list-form').action = '$action'; $('st_record_list-form').submit();")) ?>
    </li>
<?php endforeach; ?> 
<?php if (isset($mail_description_action_select_options['SELECT'])): ?>   
    <li>
        <?php echo select_tag('mail_description[action]', options_for_select($mail_description_action_select_options['SELECT'], '', array('include_custom' => __('więcej...', array(), 'stAdminGeneratorPlugin'))), array('onchange' => "if (this.selectedIndex > 0 && confirm('" . __('Jesteś pewien ze chcesz wykonać operacje', array(), 'stAdminGeneratorPlugin') . ": ' + this.options[this.selectedIndex].text)) { this.form.action = this.options[this.selectedIndex].value; this.form.submit(); }; this.selectedIndex = 0;")) ?>
    </li>
<?php endif; ?>
</ul> -->