<?php
// auto-generated by sfPropelAdmin
// date: 2009/05/18 15:48:11
?>
<td>
    <?php  //echo checkbox_tag('mail_description[selected][' . $mail_description->getPrimaryKey() . ']', $mail_description->getPrimaryKey(), false, array('class' => 'st_admin-mail_description-select', 'onchange' => "$('mail_description_action').disabled = true; var c = \$A(\$\$('input.st_admin-mail_description-select')); c.each(function(checkbox) { if (checkbox.checked) { $('mail_description_action').disabled = false; throw \$break; } })")) ?>
</td>