all: 
    storage:
        class: stSessionStorage
        param:
            session_name: soteshop
   
    controller:
        class: stFrontWebController
      
    request:
        class:  stWebRequest