propel: 
    st_product: 
        _attributes: 
            phpName: Product
            isI18N: true
            i18nTable: st_product_i18n
        opt_name: {change_column: name}
        opt_short_description: {change_column: short_description}
        opt_description: {change_column: description}
        opt_vat: {change_column: vat}
        opt_execution_time: 
            type: VARCHAR
            size: 64        
        _indexes:
            product_fk_currency_id:
                - currency_id
            parent_id_Index:
                - parent_id
                                                               
    st_product_i18n: 
        _attributes: 
            phpName: ProductI18n
        id: 
            type: integer
            required: true
            primaryKey: true
            foreignTable: st_product
            foreignReference: id
            onDelete: cascade
        culture:
            isCulture: true
            primaryKey: true
            type: VARCHAR
            size: 7
        name: 
            type: VARCHAR
            size: 255
        short_description:
            type: LONGVARCHAR
        description:
            type: MEDIUMTEXT
        search_keywords:
            type: LONGVARCHAR
        url:
            type: VARCHAR
            size: 255    
        uom:
            type: VARCHAR
            size: 10
        execution_time:
            type: VARCHAR
            size: 64
        _indexes:
            product_Index1:
                - url
                - culture
    st_product_has_recommend: 
       _attributes: 
         phpName: ProductHasRecommend
       recommend_id: 
         type: INTEGER
         primaryKey: true
         required: true
         foreignTable: st_product
         foreignReference: id
         onDelete: restrict
       product_id: 
         type: INTEGER
         primaryKey: true
         required: true
         foreignTable: st_product
         foreignReference: id
         onDelete: restrict                
