---
propel: 
  _attributes: 
    defaultIdMethod: native
    package: lib.model
  st_user_data: 
    _attributes: 
      phpName: UserData
    created_at: 
      type: timestamp
    updated_at: 
      type: timestamp
    id: 
      type: INTEGER
      primaryKey: true
      required: true
      autoIncrement: true
    sf_guard_user_id: 
      type: INTEGER
      required: true
      foreignTable: sf_guard_user
      foreignReference: id
      onDelete: cascade
    countries_id: 
      type: INTEGER
      required: true
      foreignTable: st_countries
      foreignReference: id
      onDelete: restrict
    is_billing: 
      type: BOOLEAN
    is_default: 
      type: BOOLEAN
      default: 0
    name: 
      type: VARCHAR
      size: 255
    surname: 
      type: VARCHAR
      size: 255
    full_name: 
      type: VARCHAR
      size: 128
    address: 
      type: VARCHAR
      size: 255
    address_more: 
      type: VARCHAR
      size: 255
    region: 
      type: VARCHAR
      size: 128
    street: 
      type: VARCHAR
      size: 255
    house: 
      type: VARCHAR
      size: 255
    flat: 
      type: VARCHAR
      size: 255
    code: 
      type: VARCHAR
      size: 255
    town: 
      type: VARCHAR
      size: 255
    phone: 
      type: VARCHAR
      size: 255
    company: 
      type: VARCHAR
      size: 255
    vat_number: 
      type: VARCHAR
      size: 255
    pesel: 
      type: VARCHAR
      size: 255
    crypt: 
      type: BOOLEAN
      default: 0
