<?php
// auto-generated by sfPropelAdmin
// date: 2019/05/14 13:06:43
?>
<?php 
echo st_get_admin_actions_head('style="margin-top: 10px; float: right"');

if (!$config->get('access_token'))
{
    echo st_get_admin_action('save', __('Zaloguj do Allegro'), null, array("name" => "login",));
}
else
{
    echo st_get_admin_action('save', __('Zaloguj ponownie do Allegro'), null, array("name" => "login",));
    echo st_get_admin_action('save', __('Zapisz', null, 'stAdminGeneratorPlugin'), null, array("name" => "save",));
}

echo st_get_admin_actions_foot();