<?php
// auto-generated by sfPropelAdmin
// date: 2010/06/02 14:24:21
?>
<?php
    $c = new Criteria();
    $c->add(DiscountHasProductPeer::PRODUCT_ID, $forward_parameters['product_id']);
    $assigned = $discount->countDiscountHasProducts($c);
?>
<td><?php echo $assigned || $discount->getAllProducts() ? image_tag(sfConfig::get('sf_admin_web_dir').'/images/tick.png') : '-' ?></td>
