<?php
// auto-generated by sfPropelAdmin
// date: 2009/01/13 18:48:38
?>
<?php echo st_get_admin_actions_head('style="margin-top: 10px; float: right"') ?>
    <?php if($sf_user->getAttribute('remeber')): ?>
        <?php echo st_get_admin_action('list', __('Wróć do opcji produktu', null, 'stProductOptionsBackend'), 'stProduct/optionsEdit', array ()) ?>
    <?php endif; ?>          
    <?php echo st_get_admin_action('create', __('Dodaj', null, 'stProductOptionsBackend'), 'stProduct/optionsTemplatesCreate', array ()) ?>
<?php echo st_get_admin_actions_foot() ?>
