<?php
// auto-generated by sfPropelAdmin
// date: 2009/01/30 12:27:04
?>
<?php echo st_get_admin_actions_head('style="margin-top: 10px; float: right"') ?>
      <?php echo st_get_admin_action('list', __('Lista', null, 'stAdminGeneratorPlugin'), 'stProduct/optionsTemplatesList', array ()) ?>
      <?php echo st_get_admin_action('save', __('Zapisz', null, 'stAdminGeneratorPlugin'), null, array('onclick' => "document.getElementById('sf_admin_edit_form').submit()")) ?>
<?php echo st_get_admin_actions_foot() ?>
