<?php
// auto-generated by sfPropelAdmin
// date: 2015/10/23 10:25:34
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'VisualEffect', 'stAdminGenerator') ?>

<?php st_include_partial('stProduct/header', array('related_object' => $related_object, 'title' => __('Wystaw produkty na aukcji', 
array(), 'stProduct'), 'culture' => null, 'route' => 'stProduct/allegroCustom')) ?>



<?php
?>

<?php st_include_component('stProduct', 'editMenu', array('forward_parameters' => $forward_parameters, 'related_object' => $related_object)) ?>
  

<div id="sf_admin_header">
   <?php echo stSocketView::openComponents('stProduct.allegroCustom.Header'); ?>
</div>
    
<div id="sf_admin_content" style="padding: 10px 0;">
   <?php st_include_partial('stProduct/custom_messages', array('forward_parameters' => $forward_parameters)) ?>
   <?php echo stSocketView::openComponents('stProduct.allegroCustom.Content'); ?>
</div>
    
<div id="sf_admin_footer">
   <?php echo stSocketView::openComponents('stProduct.allegroCustom.Footer'); ?>
</div>
<?php st_include_partial('stProduct/footer', array('related_object' => null, 'forward_parameters' => $forward_parameters)) ?>