<?php
// auto-generated by sfPropelAdmin
// date: 2018/12/07 11:47:44
?>

<?php use_helper('I18N', 'Date', 'Text', 'stAdminGenerator') ?>
<?php use_stylesheet('backend/stProgressBarPlugin/stProgressBarPlugin.css'); ?>

<?php echo st_get_admin_head('stProduct', __('Eksport do pliku'), __('Zarządzanie produktami w sklepie.'), array(
    0 => 'stCategory',
    1 => 'stProducer',
    2 => 'stProductGroup',
    3 => 'stQuestionPlugin',
    4 => 'appOnlineCodesPlugin',
    5 => 'stReview',
)) ?>
<?php st_include_component('stProduct', 'listMenu', array('forward_parameters' => $forward_parameters, 'product' => null)) ?>

<div id="sf_admin_header">

</div>


<div id="sf_admin_content">
    <?php if (!$export) : ?>
        <?php echo form_tag('stProduct/export', array('id' => 'sf_admin_config_form', 'class' => 'admin_form')) ?>
        <fieldset id="sf_fieldset_none" class="">
            <div id="sf_fieldset_none_slide" class="st_fieldset-content">
                <div class="form-row">
                    <label for="config_new_product_date"><?php echo __("Wybierz format exportu", array(), 'stImportExportBackend') ?></label>
                    <div class="content">
                        <ul>
                            <?php if (is_file(sfConfig::get('sf_root_dir').'/packages/appImportExportOffice2003Plugin/package.yml')): ?>
                                <li><?php echo radiobutton_tag('exporter','stExporterXml2003', array(   )) ?> <?php echo __('Export do pliku Microsoft Office 2003', array(), 'stImportExportBackend'); ?></li>
                            <?php endif ?>
                            <li><?php echo radiobutton_tag('exporter', 'stExporterCsv', array('selected' => true)) ?> <?php echo __('Export do pliku csv (UTF-8)', array(), 'stImportExportBackend'); ?></li>
                            <li><?php echo radiobutton_tag('exporter', 'stExporterCsv1250', array()) ?> <?php echo __('Export do pliku csv (Windows-1250)', array(), 'stImportExportBackend'); ?></li>
                        </ul>
                    </div>
                </div>
                <div class="form-row">
                    <label for="config_new_product_date"><?php echo __("Wybierz Profil", array(), 'stImportExportBackend') ?></label>
                    <div class="content"><?php echo select_tag('profile', options_for_select($profiles)) ?>
                        <?php echo link_to(__('Zarządzaj profilami', array(), 'stImportExportBackend'), 'stImportExportBackend/list?model=Product&for_module=stProduct'); ?>
                    </div>
                </div>

                <?php echo st_admin_get_form_field('external_images', __("Eksportuj zdjęcia do innego sklepu"), true, 'checkbox_tag') ?>
            </div>
        </fieldset>
        <?php echo st_get_admin_actions_head('style="float: right"') ?>
        <?php echo st_get_admin_action('save', __('Pobierz przykładowy plik', array(), 'stImportExportBackend'), null, array('name' => 'sample_file',)) ?>
        <?php echo st_get_admin_action('save', __('Eksportuj', array(), 'stImportExportBackend'), null, array('name' => 'save',)) ?>
        <?php echo st_get_admin_actions_foot() ?>
        </form>
    <?php else : ?>
        <div id="sf_admin_content_config">
            <?php echo form_tag('stProduct/export', array('id' => 'sf_admin_config_form')) ?>
            <fieldset id="sf_fieldset_none" class="">
                <div id="sf_fieldset_none_slide" class="st_fieldset-content">
                    <div class="form-row">
                        <?php echo $pb->showProgressBar($actual_step, true); ?>
                        <?php if ($errors) : ?>
                            <?php echo link_to_remote(__('Wyświetl błędy eksportu', array(), 'stImportExportBackend'), array('update' => 'export_log', 'url' => 'stProduct/exportLog?file=' . $logFile)) ?>.
                        <?php endif; ?>
                        <div id="export_log"></div>
                    </div>
                </div>
            </fieldset>
            </form>
        </div>
    <?php endif; ?>
</div>
<br class="st_clear_all" />

<div id="sf_admin_footer">
</div>
<?php echo st_get_admin_foot() ?>