<?php
// auto-generated by sfPropelAdmin
// date: 2012/05/24 13:41:13
?>

<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'VisualEffect', 'stAdminGenerator', 'stDate') ?>

<?php
?>

<?php st_include_partial('stProduct/header', array('related_object' => $related_object, 'title' => $online_codes->isNew() ? __('Dodaj nowy', 
array(), 'stAdminGeneratorPlugin') : __('', 
array(), 'stAdminGeneratorPlugin'), 'route' => 'stProduct/onlineCodesEdit?id='.$online_codes->getId().'&product_id='.$forward_parameters['product_id'])) ?>

<?php
if (!$online_codes->isNew() || isset($related_object) && !$related_object->isNew())
{ 
   st_include_component('stProduct', 'editMenu', array('forward_parameters' => $forward_parameters, 'related_object' => $related_object));
}
?>
  

<div id="sf_admin_content">
   <?php st_include_component('stProduct/online_codes_edit_messages', array('online_codes' => $online_codes, 'labels' => $labels, 'forward_parameters' => $forward_parameters)) ?>
   <?php st_include_partial('stProduct/online_codes_edit_form', array('online_codes' => $online_codes, 'labels' => $labels, 'forward_parameters' => $forward_parameters)) ?>
   <?php echo st_get_component('appOnlineCodesBackend','showCodeList',array('related_object'=>$related_object )); ?>
</div>

<?php st_include_partial('stProduct/footer', array('related_object' => $related_object, 'forward_parameters' => $forward_parameters)) ?>
