thumbs:
      slide:
         thumb:
            width: '909'
            height: '500'
            quality: '100'
            watermark: false
            auto_crop: true
      slide_mobile:
         thumb:
            width: '500'
            height: '489'
            quality: '100'
            watermark: false
            auto_crop: true

layout_config:
   _layouts:
      one_column:  "Jedna kolumna"
      two_column:  "Dwie kolumny"

   product_list:
      label:   "Lista produktów"
      layouts: [one_column, two_column]
      actions: ["stProduct/list", "stProduct/groupList", "stProduct/producerList"]
      default: two_column

   product_card:
      label:   "Karta produktu"
      layouts: [one_column, two_column]
      actions: ["stProduct/show"]
      default: two_column

   webpage:
      label:   "Strona www"
      layouts: [one_column, two_column]
      actions: ["stWebpageFrontend/index"]
      default: two_column

editor_config:
   slots: ~
   media:
      xs: ~
      onlyxs: "max-width: 767px"
      sm: "min-width: 768px"
      md: "min-width: 992px"
      lg: "min-width: 1200px"

   graphic:  
      logo:
         label:                        "Wygląd loga"
         display:                      [logo]
         fields:
            logo:                      {label: Logo, type: image, default: "logo.png"}

      logo_small:
         label:                        "Wygląd loga - urządzenia mobilne i małe ekrany"
         display:                      [logo_small]
         fields:
            logo_small:                {label: Logo mobile, type: image, default: "logo_small.png"}

      header_background:
         label:                        "Wygląd nagłówka strony"
         display:                      [bg_color, bg_image, repeat]
         fields:
            bg_color:                  { label: "Kolor tła", type: css, selector: "div#header", property: background-color, default: "#ffffff" }
            bg_image:                  { label: "Obraz tła", type: css, selector: "div#header", property: background-image, default: "" }
            repeat:                    { label: "Powtórzenie tła", type: css, selector: "div#header", property: background-repeat, default: "no-repeat" }

      general:
         label:                        "Wygląd ogólny"
         display:                      [text, text_muted, link, link_hover]
         fields:
            text:                      { label: "Kolor tekstu", type: css, selector: "body", property: color, default: "#333333" }
            text_muted:                { label: "Kolor tekstu wyciszonego", type: css, selector: ".text-muted", property: color, default: "#777777" }
            link:                      { label: "Kolor linku", type: css, selector: "a", property: color, default: "#444444" }
            link_hover:                { label: "Kolor linku - po najechaniu", type: css, selector: "a:hover, a:focus, a:active, .category:hover h2 a", property: color, default: "#d5230b" }

      header_navbar:
         label:                        "Wygląd górnego paska nawigacyjnego"
         display:                      [background, border, link, link_hover1, link_hover_bg1]
         fields:
            background:                { label: "Kolor tła", type: "css", selector: "nav#header-navbar", property: background-color, default: "#3B3B3B" }
            border:                    { label: "Kolor obramowania", type: "css", selector: ".btn-group .btn-navbar, #header-navbar", property: border-color, default: "#3B3B3B" }
            link:                      { label: "Kolor linku", media: "sm", type: "css", selector: "div#nav-menu > .navbar-nav > li > a", property: color, default: "#ffffff" }
            link_hover1:               { label: "Kolor linku - po najechaniu", media: "sm", type: "css", selector: "div#nav-menu .navbar-nav > li > a:hover, div#nav-menu .navbar-nav > li.active > a", property: color, default: "#ffffff" }
            link_hover_bg1:            { label: "Kolor tła linku - po najechaniu", media: "sm", type: "css", selector: "div#nav-menu .navbar-nav > li:not(.dropdown):hover > a, #nav-menu .navbar-nav > li:not(.open).active > a", property: background, default: "#b01f1e" }
         generated:
            link:
               - { selector: "#nav-button-menu.collapsed:hover .icon-bar, #nav-button-menu.collapsed .icon-bar", property: "background-color" }
               - { selector: ".more .dropdown-toggle .icon-bar", property: "background-color" }
               - { selector: ".btn-navbar.collapsed:not(:hover):focus, .btn-navbar.collapsed", property: "color" }
            link_hover1:
               - { selector: "#nav-button-menu.collapsed:hover .icon-bar, #nav-button-menu .icon-bar", property: "background-color" }
               - { selector: ".more.open .dropdown-toggle .icon-bar, .more.active .dropdown-toggle .icon-bar", property: "background-color" }
               - { selector: ".btn-navbar, .btn-navbar:active, .btn-navbar:hover, .btn-navbar:focus", property: "color" }
            link_hover_bg1:
               - { selector: ".btn-navbar, .btn-navbar:active, .btn-navbar:hover, .btn-navbar:focus", property: "background-color" }
               - { selector: "#nav-button-menu.collapsed:hover, #nav-button-menu", property: "background-color" }


      header_navbar_xs:
         label:                        "Wygląd górnego paska nawigacyjnego - urządzenia mobilne i małe ekrany"
         display:                      [link, link_hover1, link_hover_bg1, link_hover2, link_hover_bg2]
         fields:
            link:                      { label: "Kolor linku", media: "onlyxs", type: "css", selector: "div#nav-menu > .navbar-nav > li > a", property: color, default: "#444444" }
            link_hover1:               { label: "Kolor linku - po najechaniu", media: "onlyxs", type: "css", selector: "div#nav-menu .navbar-nav > li > a:hover, div#nav-menu .navbar-nav > li.active > a, div#nav-menu .dropdown-menu > li > a:hover, div#nav-menu .dropdown-menu > li.active>a", property: color, default: "#b01f1e" }
            link_hover2:               { label: "Kolor linków rozwijanych - po najechaniu", media: "onlyxs", type: "css", selector: "div#nav-menu .navbar-nav > li.dropdown > a:hover, div#nav-menu .navbar-nav > li.open > a, div#nav-menu .navbar-nav > li.active > a", property: color, default: "#b01f1e" }
            link_hover_bg1:            { label: "Kolor tła linku - po najechaniu", media: "onlyxs", type: "css", selector: "div#nav-menu .navbar-nav > li:not(.dropdown):hover > a, #nav-menu .navbar-nav > li:not(.open).active > a, div#nav-menu .dropdown-menu > li > a:hover, div#nav-menu .dropdown-menu > li.active>a", property: background, default: "#ffffff" }
            link_hover_bg2:            { label: "Kolor tła linków rozwijanych - po najechaniu", media: "onlyxs", type: "css", selector: "#nav-button-menu, div#nav-menu .navbar-nav > li.dropdown > a:hover, div#nav-menu .navbar-nav > li.open > a, div#nav-menu .navbar-nav > li.dropdown.active > a", property: background, default: "#ffffff" }

      homepage_background: ~

      background:
         label:                        Wygląd tła
         display:                      [color, image, repeat]
         fields:
            color:                     { label: "Kolor tła", type: css, selector: "body", property: background-color, default: "#f8f9f4" }
            image:                     { label: "Obraz tła", type: css, selector: "body", property: background-image, default: "" }
            repeat:                    { label: "Powtórzenie tła", type: css, selector: "body", property: background-repeat, default: "no-repeat" }

      category_box:
         label:                        Wygląd drzewa kategorii
         display:                      [color_head, bg_head, color_active]
         fields:
            color_head:                { label: "Kolor tekstu nagłówka", type: css, selector: "div#vertical-categories .panel-heading, ul#vertical-categories .panel-heading", property: color, default: "#ffffff" }
            bg_head:                   { label: "Kolor tła nagłówka", type: css, selector: "div#vertical-categories .panel-heading, ul#vertical-categories .panel-heading", property: [background-color, border-color], default: "#ed1c24" }
            color_active:              { label: "Kolor aktywnej kategorii", type: css, selector: "div#vertical-categories li.active>a, div#vertical-categories li a:hover, ul#vertical-categories li.active>a, ul#vertical-categories li a:hover, a:hover, a:focus", property: color, default: "#d5230b" }
         generated:
            bg_head:
               - { selector: "div.product_group .other_group a:before", property: "background-color" }

      info_box:
         label:                        Wygląd boksów informacyjnych
         display:                      [color_head, bg_head]
         fields:
            color_head:                { label: "Kolor tekstu nagłówka", type: css, selector: "div.product_group .panel-heading, div.product_group .panel-heading a:hover, .box-info .panel-heading", property: color, default: "#333333" }
            bg_head:                   { label: "Kolor tła nagłówka", type: css, selector: "div.product_group .panel-heading, .box-info .panel-heading", property: background-color, default: "#f5f5f5" }

      product_box:
         label:                        Wygląd boksów produktów
         display:                      [border_color, color]
         fields:
            border_color:              { label: "Kolor ramki opisu skróconego", type: css, selector: "span.back-side-product", property: border-color, default: "#F1A3A3" }
            color:                     { label: "Kolor tekstu opisu skróconego", type: css, selector: "span.back-side-product", property: color, default: "#444444" }

      product_card:
         label:                        Wygląd karty produktu
         display:                      [price_color, color_recommend]
         fields:
            price_color:               { label: "Kolor ceny", type: css, selector: "div.card .prices .price", property: color, default: "#E33034" }
            color_recommend:           { label: "Kolor podkreślenia produktów polecanych", type: css, selector: "div.card .nav-tabs > li.active > a, .card .nav-tabs > li.active > a:hover, .card .nav-tabs>li.active>a:focus", property: border-color, default: "#FF0000" }

      btn_default: 
         label:                        "Wygląd przycisku domyślnego"
         display:                      [color, background, border, color_hover, background_hover, border_hover]
         fields:
            color:                     { label: "Kolor tekstu", type: css, selector: ".btn-default", property: color, default: "#333333" }
            background:                { label: "Kolor tła", type: css, selector: ".btn-default", property: background-color, default: "#ffffff" }
            border:                    { label: "Kolor obramowania", type: css, selector: ".btn-default", property: "border-color", default: "#c7c7c7" }
            color_hover:               { label: "Kolor tekstu - po najechaniu", type: css, selector: ".btn-default:hover, .btn-default:active, .btn-default:focus", property: color, default: "#333333" }
            background_hover:          { label: "Kolor tła - po najechaniu", type: css, selector: ".btn-default:hover, .btn-default:active, btn-default:focus", property: background-color, default: "#eeeeee" }
            border_hover:              { label: "Kolor obramowania - po najechaniu", type: css, selector: ".btn-default:hover, .btn-default:active, btn-default:focus", property: "border-color", default: "#c7c7c7" }

      btn_primary: 
         label:                        "Wygląd przycisku wyróżnionego"
         display:                      [color, background, border, color_hover, background_hover, border_hover]
         fields:
            color:                     { label: "Kolor tekstu", type: css, selector: ".btn-primary, .card .btn-shopping-cart", property: color, default: "#ffffff" }
            background:                { label: "Kolor tła", type: css, selector: ".btn-primary, .card .btn-shopping-cart", property: background-color, default: "#dc1912" }
            border:                    { label: "Kolor obramowania", type: css, selector: ".btn-primary, .card .btn-shopping-cart", property: "border-color", default: "#dc1912" }
            color_hover:               { label: "Kolor tekstu - po najechaniu", type: css, selector: ".btn-primary:hover, .btn-primary:active,.btn-primary:focus, .card .btn-shopping-cart:hover, .card .btn-shopping-cart:focus, .card .btn-shopping-cart:active", property: color, default: "#ffffff" }
            background_hover:          { label: "Kolor tła - po najechaniu", type: css, selector: ".btn-primary:hover, .btn-primary:active,.btn-primary:focus, .card .btn-shopping-cart:hover, .card .btn-shopping-cart:focus, .card .btn-shopping-cart:active", property: background-color, default: "#b01f1e" }
            border_hover:              { label: "Kolor obramowania - po najechaniu", type: css, selector: ".btn-primary:hover, .btn-primary:active,.btn-primary:focus, .card .btn-shopping-cart:hover, .card .btn-shopping-cart:focus, .card .btn-shopping-cart:active", property: "border-color", default: "#b01f1e" }

      btn_shopping_cart: 
         label:                        "Wygląd przycisku koszyka"
         display:                      [color, background, border, color_hover, background_hover, border_hover]
         fields:
            color:                     { label: "Kolor tekstu", type: css, selector: ".btn-shopping-cart", property: color, default: "#333333" }
            background:                { label: "Kolor tła", type: css, selector: ".btn-shopping-cart", property: background-color, default: "#f7f7f7" }
            border:                    { label: "Kolor obramowania", type: css, selector: ".btn-shopping-cart", property: "border-color", default: "#dfdfdf" }
            color_hover:               { label: "Kolor tekstu - po najechaniu", type: css, selector: ".btn-shopping-cart:hover, .btn-shopping-cart:active,.btn-shopping-cart:focus", property: color, default: "#333333" }
            background_hover:          { label: "Kolor tła - po najechaniu", type: css, selector: ".btn-shopping-cart:hover, .btn-shopping-cart:active,.btn-shopping-cart:focus", property: background-color, default: "#eeeeee" }
            border_hover:              { label: "Kolor obramowania - po najechaniu", type: css, selector: ".btn-shopping-cart:hover, .btn-shopping-cart:active,.btn-shopping-cart:focus", property: "border-color", default: "#c7c7c7" }

      social_icon: 
         label:                        "Ikony social media"
         display:                      [icon1, icon2, icon4, icon5, icon6, icon7, icon8]
         fields:
            icon1:                     {label: "Ikona Allegro", type: image, default: "social/allegrolink.png"}
            icon2:                     {label: "Ikona Facebook", type: image, default: "social/facebook.png"}
            icon4:                     {label: "Ikona Instagram", type: image, default: "social/instagram.png"}
            icon5:                     {label: "Ikona Newsletter", type: image, default: "social/newsletter.png"}
            icon6:                     {label: "Ikona Pinterest", type: image, default: "social/pinterest.png"}
            icon7:                     {label: "Ikona Twitter", type: image, default: "social/twitter.png"}
            icon8:                     {label: "Ikona Youtube", type: image, default: "social/youtube.png"}