package:
    name: soteshop
    stability: stable
    version: 6.9.7
    summary: SOTESHOP
    description: SOTESHOP
    notes: 'Release 6.9.7'
    maintainers:
        'Marek Jakubowicz':
            role: lead
            user: marek
            email: marek.jakubowicz@sote.pl
    dependency:
        soteshop_pl: 6.6.3
