<?php
// auto-generated by sfPropelAdmin
// date: 2015/12/07 11:14:17
?>
<?php echo st_get_admin_actions_head('style="float: left"') ?>

<?php if (null !== $allegro_template->getTheme() && $allegro_template->getThemeInstance()->getThemeConfig()->hasType('graphic')): ?>
    <?php echo st_get_admin_action('reset', __('Przywróć domyślny szablon'), 'stAllegroTemplateBackend/restore?id='.$allegro_template->getId(), array("confirm" => __("Jesteś pewien?"),"name" => "restore",)) ?>
<?php endif; ?>

<?php if (!$allegro_template->getIsSystemDefault() && $allegro_template->getId()): ?>
    <?php echo st_get_admin_action('delete', __('Usuń', null, 'stAdminGeneratorPlugin'), 'stAllegroTemplateBackend/delete?id='.$allegro_template->getId(), array("confirm" => __("Jesteś pewien?"),"name" => "delete",)) ?>
<?php endif; ?>

</ul>

<?php 
echo st_get_admin_actions_head('style="float: right"'); 
$i18n = $sf_context->getI18N();
$i18n->setCurrentCatalogue('stThemeBackend');
?>
    <?php echo st_get_admin_action('list', __('Lista', null, 'stAdminGeneratorPlugin'), 'stAllegroTemplateBackend/list', array("name" => "list",)) ?>
    <?php echo st_get_admin_action('view', __('Podgląd'), null, array('name' => 'preview_save')) ?>  
    <?php echo st_get_admin_action('save', __('Zapisz', null, 'stAdminGeneratorPlugin'), null, array("name" => "save",)) ?>
<?php echo st_get_admin_actions_foot() ?>
<?php $i18n->revertToPreviousCatalogue(); ?>