<?php
// auto-generated by sfPropelAdmin
// date: 2013/11/26 12:49:43
?>
<?php if ($sf_request->hasErrors()): ?>
<div class="form-errors">
<h2><?php echo __('Popraw dane w formularzu.', array(), 'stAdminGeneratorPlugin') ?></h2>
<dl>
<?php foreach ($sf_request->getErrorNames() as $name): if (!isset($labels[$name])) continue ?>
  <dt><?php echo __($labels[$name]) ?></dt>
  <dd><?php echo $sf_request->getError($name) ?></dd>
<?php endforeach; ?>
</dl>
</div>
<?php elseif ($sf_flash->has('notice')): ?>
<div class="save-ok">
<h2><?php echo $sf_flash->get('notice') ?></h2>
</div>
<?php endif; ?>
<?php if ($sf_flash->has('warning')): ?>
<div class="form-errors">
<h2><?php echo __($sf_flash->get('warning')) ?></h2>
</div>
<?php endif; ?>

<?php if(stPoints::isIndividualTheme()): ?>
    
<div class="form-errors">
    <h2><?php echo __('Wykryto indywidualny temat graficzny').": <b style='color:black;'>".stTheme::getActiveTheme()."</b>" ?>
        <a style="float:right;" href="/backend.php/points/confirmMessage"><img src="/images/backend/beta/icons/16x16/remove.png"></a>
    </h2>
    
    <div id="message_info" style="padding: 10px;">
        <?php echo __('System punktowy działa tylko z najnowszą wersją tematów graficznych. Twój indywidualny temat graficzny')." '<b style='color:black;'>".stTheme::getActiveTheme()."</b>' ".__('musi mieć zaktualizowane pliki.') ?></br>
        <a href="#" id="show_more"><?php echo __('pokaż listę plików') ?></br></a>
    </div>
    
    <div id="message_more" style="display: none; padding: 10px;">
        <?php echo __('Lista plików tematu graficznego, które należy ręcznie zaktualizować aby system działał poprawnie:') ?><br/>
        
        <ul style="list-style: disc outside none; padding: 10px 30px;">
        <?php foreach (stPoints::verifyThemeTemplates() as $file): ?>         
            <li><?php echo $file ?></li>
        <?php endforeach; ?>
        </ul>
        
    </div>

</div>

<script type="text/javascript">
jQuery(function($) {

$(document).ready(function(){
  $("#show_more").click(function(){
    $("#message_more").toggle();
  });
});
});
</script>

<?php endif; ?>