<?php
// auto-generated by sfPropelAdmin
// date: 2013/11/26 10:14:56
?>
<?php $list_mode = $sf_user->getAttribute('list.mode', null, 'soteshop/stAdminGenerator/stPointsBackend/config'); ?>
                  
<?php if ($list_mode != 'edit'): ?>
<td class="column_created_at" style="">
   
   <?php echo ($user_points->getCreatedAt() !== null && $user_points->getCreatedAt() !== '') ? st_format_date($user_points->getCreatedAt(), "dd-MM-yyyy H:mm") : '' ?>
</td>
<?php else: ?>
<td class="column_created_at" style="">
   <?php echo ($user_points->getCreatedAt() !== null && $user_points->getCreatedAt() !== '') ? st_format_date($user_points->getCreatedAt(), "dd-MM-yyyy H:mm") : '' ?>
</td>   
<?php endif; ?>


<?php if ($list_mode != 'edit'): ?>
<td class="column_client" style="">
   
   <?php echo st_points_client_name($user_points); ?>
</td>
<?php else: ?>
<td class="column_client" style="">
   <?php echo st_points_client_name($user_points, $list_mode); ?>
</td>   
<?php endif; ?>


<?php if ($list_mode != 'edit'): ?>
<td class="column_change_points_varchar" style="">
   
   <?php echo $user_points->getChangePointsVarchar() ?>
</td>
<?php else: ?>
<td class="column_change_points_varchar" style="">
   <?php echo $user_points->getChangePointsVarchar() ?>
</td>   
<?php endif; ?>


<?php if ($list_mode != 'edit'): ?>
<td class="column_points" style="">
   
   <?php echo $user_points->getPoints() ?>
</td>
<?php else: ?>
<td class="column_points" style="">
   <?php echo $user_points->getPoints() ?>
</td>   
<?php endif; ?>


<?php if ($list_mode != 'edit'): ?>
<td class="column_change" style="">
   
   <?php echo st_points_change($user_points); ?>
</td>
<?php else: ?>
<td class="column_change" style="">
   <?php echo st_points_change($user_points, $list_mode); ?>
</td>   
<?php endif; ?>


<?php if ($list_mode != 'edit'): ?>
<td class="column_description" style="">
   <?php
    $i18n = sfContext::getInstance() -> getI18n(); 
    echo   $i18n -> __($user_points->getDescription()); 
   ?>
</td>
<?php else: ?>
<td class="column_description" style="">
   <?php
    $i18n = sfContext::getInstance() -> getI18n(); 
    echo   $i18n -> __($user_points->getDescription()); 
   ?>
</td>   
<?php endif; ?>


