<?php
// auto-generated by sfPropelAdmin
// date: 2009/03/13 14:34:34
?>
<td>
<div id="st_object_actions_td_frame">
<ul class="st_object_actions">     
      
      <li><?php echo link_to(image_tag('backend/icons/pdf_icon.png', array('alt' => __('pokaż'), 'title' => __('show'))), 'stInvoicePdf/show?id='.$invoice->getId()) ?></li>
<li><?php echo link_to(image_tag('backend/icons/pdf_download_icon.png', array('alt' => __('pobierz'), 'title' => __('download'))), 'stInvoicePdf/show?id='.$invoice->getId().'&download=true') ?></li>

      
    <?php if (method_exists($invoice, 'getIsSystemDefault') == false || (method_exists($invoice, 'getIsSystemDefault') &&  !$invoice->getIsSystemDefault())): ?>
      
    <?php endif; ?>
    
    <li><?php echo link_to(image_tag('backend/beta/icons/16x16/remove.png', array('alt' => __('delete'), 'title' => __('delete'))), 'stInvoiceBackend/confirmDelete?id='.$invoice->getId(), array (
  'post' => true,
  'confirm' => __('Usunięcie spowoduje rozbieżność w numeracji. Czy na pewno usunąć tą fakturę?'),
)) ?></li>
    
</ul>
</div>
</td>
