<?php
// auto-generated by sfPropelAdmin
// date: 2009/03/13 13:40:57
?>
<?php // echo st_get_admin_actions_head('style="margin-top: 10px; float: right"') ?>
          <?php // echo st_get_admin_action('create', __('create'), 'stInvoiceBackend/proformaCreate', array ()) ?>  <?php // echo st_get_admin_actions_foot() ?>
