<?php
// auto-generated by sfPropelAdmin
// date: 2009/03/12 14:40:36
?>
                  
<?php $value = $invoice->getNumber() ?>
<td><?php echo $value || is_numeric($value) ? $value : __('-')  ?></td>
       
<?php $value = ($invoice->getDateCreateCopy() !== null && $invoice->getDateCreateCopy() !== '') ? st_format_date($invoice->getDateCreateCopy(),'d') : '' ?>
<td><?php echo $value || is_numeric($value) ? $value : __('-')  ?></td>

<?php $value = $invoice->getOrderId() ?>
<td><?php echo $value || is_numeric($value) ? $value : __('-')  ?></td>

<?php $value = st_get_component('stInvoiceBackend', 'company', array('type' => 'list', 'invoice' => isset($invoice) ? $invoice : null, 'forward_parameters' => $forward_parameters)) ?>
<td><?php echo $value || is_numeric($value) ? $value : __('-')  ?></td>
       
<?php $value = st_get_component('stInvoiceBackend', 'vatNumber', array('type' => 'list', 'invoice' => isset($invoice) ? $invoice : null, 'forward_parameters' => $forward_parameters)) ?>
<td><?php echo $value || is_numeric($value) ? $value : __('-')  ?></td>

<?php $value = st_get_component('stInvoiceBackend', 'fullName', array('type' => 'list', 'invoice' => isset($invoice) ? $invoice : null, 'forward_parameters' => $forward_parameters)) ?>
<td><?php echo $value || is_numeric($value) ? $value : __('-')  ?></td>
