<?php
// auto-generated by sfPropelAdmin
// date: 2009/03/13 14:34:34
?>
<td width="50">
<ul class="st_object_actions"> 
   
<li><?php echo link_to(image_tag('backend/icons/pdf_icon.png', array('alt' => __('pokaż'), 'title' => __('show'))), 'stInvoicePdf/show?id='.$invoice->getId()) ?></li>
<li><?php echo link_to(image_tag('backend/icons/pdf_download_icon.png', array('alt' => __('pobierz'), 'title' => __('download'))), 'stInvoicePdf/show?id='.$invoice->getId().'&download=true') ?></li>

<?php if (method_exists($invoice, 'getIsSystemDefault') == false || (method_exists($invoice, 'getIsSystemDefault') &&  !$invoice->getIsSystemDefault())): ?>  
<li><a href="<?php echo url_for('stInvoiceBackend/requestDelete?id='.$invoice->getId()) ?>" onclick="return confirm('<?php echo __('Jesteś pewien?') ?>');"><img src="/images/backend/beta/icons/16x16/remove.png" title="<?php echo __('delete') ?>" class="tooltip" /></a></li>  
<?php endif; ?>

   </ul>
</td>
