<?php
// auto-generated by sfPropelAdmin
// date: 2010/05/24 11:41:09
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'VisualEffect', 'stAdminGenerator') ?>

<?php echo st_get_admin_head('stInvoicePlugin', __('Faktura'), __(''), NULL) ?>
    <?php st_include_component('stInvoiceBackend', 'listMenu', array('forward_parameters' => $forward_parameters, 'invoice' => null)) ?>
  

    <div id="sf_admin_header">
        <?php echo stSocketView::openComponents('stInvoiceBackend.viewCustom.Header'); ?>
    </div>
    
    <div id="sf_admin_content">
        <?php echo stSocketView::openComponents('stInvoiceBackend.viewCustom.Content'); ?>
    </div>
    
    <div id="sf_admin_footer">
        <?php echo stSocketView::openComponents('stInvoiceBackend.viewCustom.Footer'); ?>
    </div>
<br class="st_clear_all">
<?php echo st_get_admin_foot() ?>