<?php
// auto-generated by sfPropelAdmin
// date: 2016/01/14 15:36:10
?>
<?php echo form_tag('stTrustedShopsBackend/save', array(
  'id'        => 'admin_edit_form',
  'name'      => 'admin_edit_form',
  'class'     => 'admin_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($trusted_shops, 'getId') ?>


<fieldset id="sf_fieldset__">
<h2><?php echo __(' ', null, 'stTrustedShopsBackend') ?></h2>
<div class="content" id="sf_fieldset___slide">
<?php if ($trusted_shops->getPrimaryKey()): ?>
<?php if (!$sf_user->getParameter('hide', false,'stTrustedShopsBackend/edit/fields/shop')): ?>
<div class="row row_shop">

<label for="trusted_shops_shop">
  <?php echo __($labels['trusted_shops{shop}'], array(), 'stTrustedShopsBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('trusted_shops{shop}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('trusted_shops{shop}')): ?>
    <?php echo form_error('trusted_shops{shop}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo st_get_partial('stTrustedShopsBackend/shop', array('type' => 'edit', 'trusted_shops' => $trusted_shops, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>
<?php endif; ?>

<?php if (!$sf_user->getParameter('hide', false,'stTrustedShopsBackend/edit/fields/certificate')): ?>
<div class="row row_certificate">

<label for="trusted_shops_certificate">
  <?php echo __($labels['trusted_shops{certificate}'], array(), 'stTrustedShopsBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('trusted_shops{certificate}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('trusted_shops{certificate}')): ?>
    <?php echo form_error('trusted_shops{certificate}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo st_get_partial('stTrustedShopsBackend/certificate', array('type' => 'edit', 'trusted_shops' => $trusted_shops, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

</div>
</fieldset>
<?php if ($trusted_shops->getPrimaryKey()): ?>
<fieldset id="sf_fieldset_ochrona_kupuj__cych">
<h2><?php echo __('Ochrona kupujących', null, 'stTrustedShopsBackend') ?></h2>
<div class="content" id="sf_fieldset_ochrona_kupuj__cych_slide">
<?php if ($trusted_shops->getPrimaryKey()): ?>
<?php if (!$sf_user->getParameter('hide', false,'stTrustedShopsBackend/edit/fields/username')): ?>
<div class="row row_username">

<label for="trusted_shops_username">
  <?php echo __($labels['trusted_shops{username}'], array(), 'stTrustedShopsBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('trusted_shops{username}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('trusted_shops{username}')): ?>
    <?php echo form_error('trusted_shops{username}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo st_get_partial('stTrustedShopsBackend/username', array('type' => 'edit', 'trusted_shops' => $trusted_shops, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>
<?php endif; ?>

<?php if ($trusted_shops->getPrimaryKey()): ?>
<?php if (!$sf_user->getParameter('hide', false,'stTrustedShopsBackend/edit/fields/password')): ?>
<div class="row row_password">

<label for="trusted_shops_password">
  <?php echo __($labels['trusted_shops{password}'], array(), 'stTrustedShopsBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('trusted_shops{password}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('trusted_shops{password}')): ?>
    <?php echo form_error('trusted_shops{password}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo st_get_partial('stTrustedShopsBackend/password', array('type' => 'edit', 'trusted_shops' => $trusted_shops, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>
<?php endif; ?>

</div>
</fieldset>

<fieldset id="sf_fieldset_przypisanie_metod_p__atno__ci">
<h2><?php echo __('Przypisanie metod płatności', null, 'stTrustedShopsBackend') ?></h2>
<div class="content" id="sf_fieldset_przypisanie_metod_p__atno__ci_slide">
<?php if ($trusted_shops->getPrimaryKey()): ?>
<?php if (!$sf_user->getParameter('hide', false,'stTrustedShopsBackend/edit/fields/payments')): ?>
<div class="row row_payments">

<label for="trusted_shops_payments">
  <?php echo __($labels['trusted_shops{payments}'], array(), 'stTrustedShopsBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('trusted_shops{payments}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('trusted_shops{payments}')): ?>
    <?php echo form_error('trusted_shops{payments}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo st_get_partial('stTrustedShopsBackend/payments', array('type' => 'edit', 'trusted_shops' => $trusted_shops, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>
<?php endif; ?>

</div>
</fieldset>

<fieldset id="sf_fieldset_trusted_badge">
<h2><?php echo __('Trustbadge', null, 'stTrustedShopsBackend') ?></h2>
<div class="content" id="sf_fieldset_trusted_badge_slide">
<?php if ($trusted_shops->getPrimaryKey()): ?>
<?php if (!$sf_user->getParameter('hide', false,'stTrustedShopsBackend/edit/fields/trustbadge_code')): ?>
<div class="row row_trustbadge_code">

<label for="trusted_shops_trustbadge_code">
  <?php echo __($labels['trusted_shops{trustbadge_code}'], array(), 'stTrustedShopsBackend'); ?></label>
  <div class="field<?php if ($sf_request->hasError('trusted_shops{trustbadge_code}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('trusted_shops{trustbadge_code}')): ?>
    <?php echo form_error('trusted_shops{trustbadge_code}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo st_get_partial('stTrustedShopsBackend/trustbadge_code', array('type' => 'edit', 'trusted_shops' => $trusted_shops, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>
<?php endif; ?>

</div>
</fieldset>

<?php endif; ?>

<div id="edit_actions"><?php st_include_partial('edit_actions', array('trusted_shops' => $trusted_shops, 'forward_parameters' => $forward_parameters)) ?></div>

</form>

<script type="text/javascript">
jQuery(function($) {
    $(document).ready(function() {
        $('#edit_actions').stickyBox();
    });

});
</script>
