<?php
// auto-generated by sfPropelAdmin
// date: 2015/10/14 09:13:09
?>
<?php echo form_tag('stProductGroup/save?culture=' . $product_group->getCulture().'', array(
  'id'        => 'admin_edit_form',
  'name'      => 'admin_edit_form',
  'class'     => 'admin_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($product_group, 'getId') ?>


<fieldset id="sf_fieldset_none">
<div class="content" id="sf_fieldset_none_slide">
<?php if (!$sf_user->getParameter('hide', false,'stProductGroup/edit/fields/name')): ?>
<div class="row row_name">

<label for="product_group_name">
  <?php echo __($labels['product_group{name}'], array(), 'stProductGroup'); ?></label>
  <div class="field<?php if ($sf_request->hasError('product_group{name}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('product_group{name}')): ?>
    <?php echo form_error('product_group{name}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo object_input_tag($product_group, 'getName', array (
  'control_name' => 'product_group[name]',
  'size' => 50,
)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

<?php if (!$sf_user->getParameter('hide', false,'stProductGroup/edit/fields/default_product_group')): ?>
<div class="row row_default_product_group">

<label for="product_group_default_product_group">
  <?php echo __($labels['product_group{default_product_group}'], array(), 'stProductGroup'); ?></label>
  <div class="field<?php if ($sf_request->hasError('product_group{default_product_group}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('product_group{default_product_group}')): ?>
    <?php echo form_error('product_group{default_product_group}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo st_get_component('stProductGroup','defaultProductGroup', array('type' => 'edit', 'product_group' => $product_group, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

<?php if (!$sf_user->getParameter('hide', false,'stProductGroup/edit/fields/new') && $product_group->getProductGroup()=="NEW"): ?>
<div class="row row_new">
  <div>
<?php if ($sf_request->hasError('product_group{new}')): ?>
    <?php echo form_error('product_group{new}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo st_get_partial('stProductGroup/new', array('type' => 'edit', 'product_group' => $product_group, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object, 'config' => $config, 'config_group' => $config_group)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

<?php if (!$sf_user->getParameter('hide', false,'stProductGroup/edit/fields/product_limit')): ?>
<div class="row row_product_limit">

<label for="product_group_product_limit">
  <?php echo __($labels['product_group{product_limit}'], array(), 'stProductGroup'); ?></label>
  <div class="field<?php if ($sf_request->hasError('product_group{product_limit}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('product_group{product_limit}')): ?>
    <?php echo form_error('product_group{product_limit}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo object_input_tag($product_group, 'getProductLimit', array (
  'size' => 3,
  'control_name' => 'product_group[product_limit]',
)); ?> 


  <div class="clr"></div>
  </div>
</div>

<?php endif; ?>

</div>
</fieldset>

<fieldset id="sf_fieldset_etykieta">
<h2><?php echo __('Etykieta', null, 'stProductGroup') ?></h2>
<div class="content" id="sf_fieldset_etykieta_slide">
<?php if (!$sf_user->getParameter('hide', false,'stProductGroup/edit/fields/image')): ?>
<div class="row row_image">

<label for="product_group_image">
  <?php echo __($labels['product_group{image}'], array(), 'stProductGroup'); ?></label>
  <div class="field<?php if ($sf_request->hasError('product_group{image}')): ?> form-error<?php endif; ?>">
<?php if ($sf_request->hasError('product_group{image}')): ?>
    <?php echo form_error('product_group{image}', array('class' => 'form-error-msg')) ?>
<?php endif; ?>

 <?php echo st_get_partial('stProductGroup/image', array('type' => 'edit', 'product_group' => $product_group, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object)); ?> 


  <div class="clr"></div>
  </div>
</div>
<?php endif; ?>

</div>
</fieldset>

<div id="edit_actions"><?php st_include_partial('edit_actions', array('product_group' => $product_group, 'forward_parameters' => $forward_parameters)) ?></div>

</form>

<script type="text/javascript">
jQuery(function($) {
    $(document).ready(function() {
        $('#edit_actions').stickyBox();
    });

});
</script>
