<?php
// auto-generated by sfPropelAdmin
// date: 2015/10/14 09:13:09
?>

<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'VisualEffect', 'stAdminGenerator', 'stDate') ?>


<?php
?>

<?php st_include_partial('stProductGroup/header', array('related_object' => $related_object, 'title' => $product_group->isNew() ? __('Dodaj nowy', 
array(), 'stAdminGeneratorPlugin') : __('Edycja grupy produktów', 
array(), 'stProductGroup'), 'culture' => !$product_group->isNew() ? $product_group->getCulture() : null, 'route' => 'stProductGroup/edit?id='.$product_group->getId())) ?>

<?php
if (!$product_group->isNew() || isset($related_object) && !$related_object->isNew())
{ 
   st_include_component('stProductGroup', 'editMenu', array('forward_parameters' => $forward_parameters, 'related_object' => $related_object));
}
?>
  

<div id="sf_admin_content">
   <?php st_include_partial('stProductGroup/edit_messages', array('product_group' => $product_group, 'labels' => $labels, 'forward_parameters' => $forward_parameters)) ?>
   <?php st_include_partial('stProductGroup/edit_form', array('product_group' => $product_group, 'labels' => $labels, 'forward_parameters' => $forward_parameters, 'related_object' => $related_object, 'config' => $config, 'config_group' => $config_group)) ?>
</div>

<?php st_include_partial('stProductGroup/footer', array('related_object' => $related_object, 'forward_parameters' => $forward_parameters)) ?>