<?php
// auto-generated by sfPropelAdmin
// date: 2008/11/07 09:50:33
?>
                  
       
<?php $value = $product_options_template->getName() ?>
<td><?php echo link_to($value || is_numeric($value) ? $value : __('-') , st_replace_forward_parameters("stProductOptionsBackend/useTemplate?template_id={$product_options_template->getId()}&product_id=%%forward_parameters.product_id%%", $forward_parameters)) ?></td>
