---
package:
  name: stTranslationItPlugin
  stability: stable
  version: 7.0.5.0
  summary: Tlumaczenia w jezyku wloskim.
  description: Tlumaczenia w jezyku wloskim.
  notes: |
    - Aktualizacja tlumaczen.
  maintainers:
    Michal Prochowski:
      role: lead
      user: michal
      email: michal.prochowski@sote.pl
  dependency: 
    stLanguagePlugin: 1.1.0.14
