---
package: 
  name: stWebApiPlugin
  stability: stable
  version: 7.5.0.1
  summary: API
  description: API
  notes: |
    - Dodanie obslugi parametrow width, height, depth dla metod stProduct::GetProduct, stProduct::GetProductByCode, stProduct::GetProductList, stProduct::UpdateProduct, stProduct::UpdateProductByCode, stProduct::AddProduct
  maintainers: 
    Michal Prochowski: 
      role: lead
      user: michal
      email: michal.prochowski@sote.pl
  dependency: 
    stFrontend: 1.0.8
