sfGuardUser:
  admin:
    username:       
    password:       
    is_super_admin: 1
  sfGuardUser_2:
    username:       jan@example.com
    password:       
    is_super_admin: 0
    
sfGuardPermission:
  sfGuardPermission_1:
    name:           admin
    description:    admin permission
  sfGuardPermission_2:
    name:           user
    description:    user permission
  sfGuardPermission_3:
    name:           backend
    description:    backend permission
  sfGuardPermission_4:
    name:           update
    description:    update permission
    
sfGuardGroup:
  sfGuardGroup_1:
    name:           admin
    description:    admin group
  sfGuardGroup_2:
    name:           user
    description:    Grupa użytkownika sklepu

sfGuardUserGroup:
  sfGuardUserGroup_1:
    group_id:       sfGuardGroup_2
    user_id:        sfGuardUser_2
  sfGuardUserGroup_2:
    group_id:       sfGuardGroup_1
    user_id:        admin
    
sfGuardGroupPermission:
  sfGuardGroupPermission_1:
    group_id:       sfGuardGroup_1
    permission_id:  sfGuardPermission_1
  sfGuardGroupPermission_2:
    group_id:       sfGuardGroup_2
    permission_id:  sfGuardPermission_2
    
sfGuardUserPermission:
  sfGuardGroupPermission_1:
    user_id:        admin
    permission_id:  sfGuardPermission_3
  sfGuardGroupPermission_2:
    user_id:        admin
    permission_id:  sfGuardPermission_4