<?php
// auto-generated by sfPropelAdmin
// date: 2008/12/04 16:37:30
?>
<td>
<div id="st_object_actions_td_frame" style="width: 80px;">
<ul class="st_object_actions">     
  
      
    
  <li><?php echo link_to(image_tag('backend/category_tree/arrows/arrow_up.png', array('alt' => __('moveUp'), 'title' => __('moveUp'))), 'stWebpageGroupHasWebpageBackend/moveUp?id='.$webpage_group_has_webpage->getId()) ?></li>
  
    
  
      
    
  <li><?php echo link_to(image_tag('backend/category_tree/arrows/arrow_down.png', array('alt' => __('moveDown'), 'title' => __('moveDown'))), 'stWebpageGroupHasWebpageBackend/moveDown?id='.$webpage_group_has_webpage->getId()) ?></li>
  
    
  
      
    <?php if (method_exists($webpage_group_has_webpage, 'getIsSystemDefault') == false || (method_exists($webpage_group_has_webpage, 'getIsSystemDefault') &&  !$webpage_group_has_webpage->getIsSystemDefault())): ?>
    
  <li><?php echo link_to(image_tag('backend/icons/delete.gif', array('alt' => __('delete'), 'title' => __('delete'))), 'stWebpageGroupHasWebpageBackend/delete?id='.$webpage_group_has_webpage->getId(), array (
  'post' => true,
  'confirm' => __('Jesteś pewien?'),
)) ?></li>
  
    <?php endif; ?>
    
</ul>
</div>
</td>
