<?php
// auto-generated by sfPropelAdmin
// date: 2011/05/06 11:09:50
?>
<?php $list_mode = $sf_user->getAttribute('list.mode', null, 'soteshop/stAdminGenerator/stSlideBannerBackend/config'); ?>
                  

<?php $value = $slide_banner->getImage() ?>
<td>
   <?php if($slide_banner->getImage()): ?>
   <img src="/uploads<?php echo $slide_banner->getImage(); ?>" alt="" style="width: 133px; margin: 3px;" >
   <?php endif; ?>
</td>


<?php 
	$id = $slide_banner->getLanguageId();
	$c = new Criteria();
    $c->add(LanguagePeer::ID, $id);
    $language = LanguagePeer::doSelectOne($c);
?>


<td style="text-align: left;">
<?php if($language->getActiveImage()):?>
    <?php echo image_tag('/'.sfConfig::get('sf_upload_dir_name')."/stLanguagePlugin/".$language->getActiveImage())?>
<?php else:?>
    <?php echo $language; ?>
<?php endif;?>
</td>


<?php if(stConfig::getInstance('stSlideBannerBackend')->get('group_field_on')==1):?>

<?php if ($list_mode != 'edit'): ?>
<td class="column_group_name" style="">
   
   <?php echo $slide_banner->getGroupName() ?>
</td>
<?php else: ?>
<td class="column_group_name" style="">
   <?php echo $slide_banner->getGroupName() ?>
</td>   
<?php endif; ?>

<?php endif; ?>


<?php $value = $slide_banner->getIsActive() ? image_tag('/images/backend/beta/icons/16x16/tick.png') : '' ?>
<td style="text-align: left;"><?php echo $value || is_numeric($value) ? $value : __('-')  ?></td>