<?php
// auto-generated by sfPropelAdmin
// date: 2015/11/18 16:49:09
?>
<th id="sf_admin_list_th_image" style="">

<?php if (isset($for_filters)): ?>
<?php echo __('Slajd', array(), 'stSlideBannerBackend') ?>
<?php else: ?>
<?php if ($sf_user->getAttribute('type', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'asc'): ?>
<a href="<?php echo st_url_for('stSlideBannerBackend/list?sort=image'.'&type=desc') ?>?page=<?php echo $pager->getPage() ?>">
<?php echo __('Slajd', array(), 'stSlideBannerBackend') ?>
</a>
<?php if ($sf_user->getAttribute('sort', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'image'): ?>
<img src="/images/backend/icons/desc.png" style="vertical-align: middle; width: 13px" />
<?php endif; ?>
<?php else: ?>
<a href="<?php echo st_url_for('stSlideBannerBackend/list?sort=image'.'&type=asc') ?>?page=<?php echo $pager->getPage() ?>">
<?php echo __('Slajd', array(), 'stSlideBannerBackend') ?>
</a>
<?php if ($sf_user->getAttribute('sort', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'image'): ?>
<img src="/images/backend/icons/asc.png" style="vertical-align: middle; width: 13px" />
<?php endif; ?>
<?php endif; ?>
<?php endif; ?>
</th>
<th id="sf_admin_list_th_opt_culture" style="">

<?php if (isset($for_filters)): ?>
<?php echo __('Wersja językowa', array(), 'stSlideBannerBackend') ?>
<?php else: ?>
<?php if ($sf_user->getAttribute('type', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'asc'): ?>
<a href="<?php echo st_url_for('stSlideBannerBackend/list?sort=opt_culture'.'&type=desc') ?>?page=<?php echo $pager->getPage() ?>">
<?php echo __('Wersja językowa', array(), 'stSlideBannerBackend') ?>
</a>
<?php if ($sf_user->getAttribute('sort', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'opt_culture'): ?>
<img src="/images/backend/icons/desc.png" style="vertical-align: middle; width: 13px" />
<?php endif; ?>
<?php else: ?>
<a href="<?php echo st_url_for('stSlideBannerBackend/list?sort=opt_culture'.'&type=asc') ?>?page=<?php echo $pager->getPage() ?>">
<?php echo __('Wersja językowa', array(), 'stSlideBannerBackend') ?>
</a>
<?php if ($sf_user->getAttribute('sort', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'opt_culture'): ?>
<img src="/images/backend/icons/asc.png" style="vertical-align: middle; width: 13px" />
<?php endif; ?>
<?php endif; ?>
<?php endif; ?>
</th>
<?php if(stConfig::getInstance('stSlideBannerBackend')->get('group_field_on')==1):?>
<th id="sf_admin_list_th_group_name" style="">

<?php if (isset($for_filters)): ?>
<?php echo __('Nazwa grupy', array(), 'stSlideBannerBackend') ?>
<?php else: ?>
<?php if ($sf_user->getAttribute('type', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'asc'): ?>
<a href="<?php echo st_url_for('stSlideBannerBackend/list?sort=group_name'.'&type=desc') ?>?page=<?php echo $pager->getPage() ?>">
<?php echo __('Nazwa grupy', array(), 'stSlideBannerBackend') ?>
</a>
<?php if ($sf_user->getAttribute('sort', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'group_name'): ?>
<img src="/images/backend/icons/desc.png" style="vertical-align: middle; width: 13px" />
<?php endif; ?>
<?php else: ?>
<a href="<?php echo st_url_for('stSlideBannerBackend/list?sort=group_name'.'&type=asc') ?>?page=<?php echo $pager->getPage() ?>">
<?php echo __('Nazwa grupy', array(), 'stSlideBannerBackend') ?>
</a>
<?php if ($sf_user->getAttribute('sort', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'group_name'): ?>
<img src="/images/backend/icons/asc.png" style="vertical-align: middle; width: 13px" />
<?php endif; ?>
<?php endif; ?>
<?php endif; ?>
</th>
<?php endif; ?>

<th id="sf_admin_list_th_is_active" style="">

<?php if (isset($for_filters)): ?>
<?php echo __('Aktywny', array(), 'stSlideBannerBackend') ?>
<?php else: ?>
<?php if ($sf_user->getAttribute('type', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'asc'): ?>
<a href="<?php echo st_url_for('stSlideBannerBackend/list?sort=is_active'.'&type=desc') ?>?page=<?php echo $pager->getPage() ?>">
<?php echo __('Aktywny', array(), 'stSlideBannerBackend') ?>
</a>
<?php if ($sf_user->getAttribute('sort', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'is_active'): ?>
<img src="/images/backend/icons/desc.png" style="vertical-align: middle; width: 13px" />
<?php endif; ?>
<?php else: ?>
<a href="<?php echo st_url_for('stSlideBannerBackend/list?sort=is_active'.'&type=asc') ?>?page=<?php echo $pager->getPage() ?>">
<?php echo __('Aktywny', array(), 'stSlideBannerBackend') ?>
</a>
<?php if ($sf_user->getAttribute('sort', null, 'sf_admin/autoStSlideBannerBackend/sort') == 'is_active'): ?>
<img src="/images/backend/icons/asc.png" style="vertical-align: middle; width: 13px" />
<?php endif; ?>
<?php endif; ?>
<?php endif; ?>
</th>
