<?php
// auto-generated by sfPropelAdmin
// date: 2010/05/24 14:55:44
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'VisualEffect', 'stAdminGenerator') ?>

<?php echo st_get_admin_head('stSlideBannerPlugin', __('Konfiguracja'), __('Zarządzanie banerem na stronie głównej.'), NULL) ?>
    <?php st_include_component('stSlideBannerBackend', 'listMenu', array('forward_parameters' => $forward_parameters, 'baner' => null)) ?>
    <?php st_include_partial('stAdminGenerator/message') ?>

    <div id="sf_admin_header">
        <?php echo stSocketView::openComponents('stSlideBannerBackend.configCustom.Header'); ?>
    </div>
    
    <div id="sf_admin_content">
        <?php echo stSocketView::openComponents('stSlideBannerBackend.configCustom.Content'); ?>
    </div>
    
    <div id="sf_admin_footer">
        <?php echo stSocketView::openComponents('stSlideBannerBackend.configCustom.Footer'); ?>
    </div>
<br class="st_clear_all">
<?php echo st_get_admin_foot() ?>