---
package: 
  name: stSwiftPlugin
  stability: stable
  version: 1.2.0.2
  summary: Swift
  description: Swift
  notes: |
    - Aktualizacja bibliotek do wersji 5.0.0
  maintainers: 
    Marcin Butlak: 
      role: lead
      user: marcin
      email: marcin.butlak@sote.pl
